insert into username
values (default, 'BOT', 'LOGIN');

insert into spaceship_type
values (default,
        'Грузовой транспорт',
        'Медленный, бронированный и грузоподъёмный. Слабое вооружения.'),
       (default,
        'Дипломатический корабль',
        'Быстрый, броннированный, с неплохим вооружением. Используется для дипломатический миссий.'),
       (default,
        'Пассажирский Лайнер',
        'Среднескоростной и бронированный, служит для транспортировки пассажиров. Слабое вооружения.'),
       (default,
        'Военный корабль',
        'корабль средней скорости, хорошее вооружение, хорошая броня.'),
       (default,
        'Пиратский корабль',
        'Быстрый корабль, среднее вооружение, но слабая защита корпуса. Лучшее что' ||
        ' можно было собрать из космичекого мусора'),
       (default,
        'Корабль Рейнджера',
        'Корабль средней скорости, хорошее вооружение и броня.'),
       (default,
        'Флагман',
        'Является крупным военным кораблём. Крайне медлительный, но имеет прекрасную прочность' ||
        'корпуса и передовое вооружение');

insert into spacebase_type
values (default,
        'Медицинский центр',
        'Медицинский центр - место где можно подправить руки, ноги и другие конечности.',
        'MB.png',
        -32,
        100),
       (default,
        'Бизнес-центр',
        'Космический банк. Ну что о нём можно сказать... Работает как любой другой банк.',
        'BC.png',
        0,
        100),
       (default,
        'Военная база',
        'Космическая военная база. О ней мало какой-либо информации ввиду её секретности.',
        'WB.png',
        75,
        100),
       (default,
        'Черный рынок',
        'Место скопления воров и мошенников. Здесь можно прибрести не совсем законные вещи.',
        'PB.png',
        -100,
        100),
       (default,
        'Научная станция',
        'Научная станция - отличное место для приобретения передовых технологий.',
        'SB.png',
        20,
        100),
       (default, 'Доминион',
        'Удивительно, но у пиратского союза также есть своя космическая база. Благодаря своей ' ||
        'удивительной технологии менять своё месторасположение в галактике, на космическую базу Доминион' ||
        ' ещё никому не удалось напасть.',
        'Domin.png',
        -100,
        -25),
       (default,
        'Центр рейнджеров',
        'Проводят классификацию рейнджеров. Информируют планеты о деятельности тех или иных рейнджеров',
        'RB.png',
        25,
        100);

insert into politics
values (default,
        'Абсолютная монархия',
        'Форма правления или государственного устройства, при котором пост официального главой государства закреплён за монархом.'),
       (default,
        'Демократия',
        'Форма правления, при которой народ имеет право выбирать своих правящих законодателей'),
       (default,
        'Анархия',
        'Здесь нет власти, правил или законов. Однако слабые все равно вынуждены подчиняться сильным'),
       (default,
        'Республика',
        'Форма государственного правления, при которой все органы государственной власти либо избираются на определённый срок,' ||
        ' либо формируются общенациональными представительными учреждениями (например, парламентом), а граждане обладают личными и политическими правами.');

insert into economics
values (default, 'Аграрная', 'Преобладает сельское хозяйство.'),
       (default, 'Индустриальная', 'Преобладает промышленность с гибкими динамичными структурами.'),
       (default, 'Смешанная', 'Развитие аграрной и индустриальной промышленностей идёт равномено.');

insert into race
values (default, 'Человек', 'Две руки, две ноги - на макаку похож.'),
       (default, 'Фэяне', 'Раса гуманоидов-гермафродитов с большим мозгом и фасеточными глазами.'),
       (default, 'Малок',
        'Крупные, мощного телосложения гуманоиды. Для них характерна огромная физическая сила, ' || 'выносливость, ' ||
        'Высокая сопротивляемость природным факторам, не слишком активная мыслительная деятельность.'),
       (default, 'Гаалец',
        'Гуманоиды, тысячелетиями модифицирующие свою биологическую форму путем генетических модификаций эмбрионов.'),
       (default, 'Пеленг',
        'Относятся к виду жаброшеих амфибий. Этот вид существ одинаково хорошо приспособлен для обитания как в жидкой среде, так и на суше.');


-------SECTOR---------
insert into sector(name) values
('Атланта'),
('Фаави'),
('Таолис'),
('Нароби'),
('Реггет'),
('Эльта'),
('Карагон');

-------SYSTEMS---------
insert into system(name, sector_id, image) values
('Витта Прайонис', (select sector.id from sector where sector.name = 'Атланта'), 's5.png'),
('Шеат', (select sector.id from sector where sector.name = 'Атланта'), 's4.png'),
('Краа', (select sector.id from sector where sector.name = 'Атланта'), 's3.png'),
('Тураис', (select sector.id from sector where sector.name = 'Атланта'), 's8.png'),

('Хезе', (select sector.id from sector where sector.name = 'Фаави'), 's5.png'),
('Таллот', (select sector.id from sector where sector.name = 'Фаави'), 's8.png'),
('Ругулус', (select sector.id from sector where sector.name = 'Фаави'), 's7.png'),

('Гевер', (select sector.id from sector where sector.name = 'Таолис'), 's7.png'),
('Наккар', (select sector.id from sector where sector.name = 'Таолис'), 's3.png'),
('Селиостр', (select sector.id from sector where sector.name = 'Таолис'), 's3.png'),

('Укфал', (select sector.id from sector where sector.name = 'Нароби'), 's5.png'),
('Юфалли', (select sector.id from sector where sector.name = 'Нароби'), 's2.png'),
('Денеб', (select sector.id from sector where sector.name = 'Нароби'), 's4.png'),
('Атрия', (select sector.id from sector where sector.name = 'Нароби'), 's5.png'),

('Фелгест', (select sector.id from sector where sector.name = 'Реггет'), 's2.png'),
('Завия', (select sector.id from sector where sector.name = 'Реггет'), 's6.png'),
('Диадема', (select sector.id from sector where sector.name = 'Реггет'), 's3.png'),

('Маркаб', (select sector.id from sector where sector.name = 'Эльта'), 's5.png'),
('Аркабе', (select sector.id from sector where sector.name = 'Эльта'), 's10.png'),
('Канопус', (select sector.id from sector where sector.name = 'Эльта'), 's3.png'),
('Сезмен', (select sector.id from sector where sector.name = 'Эльта'), 's14.png'),
('Муррац', (select sector.id from sector where sector.name = 'Эльта'), 's4.png'),

('Бетельгейзе', (select sector.id from sector where sector.name = 'Карагон'), 's5.png'),
('Кефрон', (select sector.id from sector where sector.name = 'Карагон'), 's6.png'),
('Солнце', (select sector.id from sector where sector.name = 'Карагон'), 's6.png');


-------PLANETS-------

insert into planet(name, citizens, politics_id, economics_id, system_id, coord_x, coord_y, image) values
('Невод', 0, null, null, (select system.id from system where system.name = 'Витта Прайонис'), 1140, 796, 'p5.png'),
('Омилит', 1703, 3, 1, (select system.id from system where system.name = 'Витта Прайонис'), -360, -233, 'p7.png'),
('Атрий', 2325, 3, 1, (select system.id from system where system.name = 'Витта Прайонис'), -1264, -735, 'p7.png'),
('Прожог', 30, 3, 2, (select system.id from system where system.name = 'Витта Прайонис'), 307, 100, 'p3.png'),

('Клёцка', 0, null, null, (select system.id from system where system.name = 'Шеат'), 157, 521, 'p3.png'),
('Бирка', 5110, 2, 1, (select system.id from system where system.name = 'Шеат'), 1283, 138, 'p2.png'),
('Купава', 9977, 1, 1, (select system.id from system where system.name = 'Шеат'), 542, 955, 'p6.png'),

('Гусли', 2328, 1, 2, (select system.id from system where system.name = 'Краа'), 586, -790, 'p8.png'),
('Бекас', 8034, 1, 2, (select system.id from system where system.name = 'Краа'), -196, -601, 'p4.png'),
('Венед', 4987, 1, 1, (select system.id from system where system.name = 'Краа'), 317, 115, 'p7.png'),
('Твердо', 1871, 3, 1, (select system.id from system where system.name = 'Краа'), 1183, 1281, 'p4.png'),
('Кайчи', 0, null, null, (select system.id from system where system.name = 'Краа'), -468, 1060, 'p5.png'),
('Заплыв', 0, null, null, (select system.id from system where system.name = 'Краа'), 291, 768, 'p2.png'),

('Тагиш', 0, null, null, (select system.id from system where system.name = 'Тураис'), -51, -872, 'p3.png'),
('Накол', 0, null, null, (select system.id from system where system.name = 'Тураис'), 862, 482, 'p3.png'),
('Завязь', 0, null, null, (select system.id from system where system.name = 'Тураис'), 1265, 309, 'p4.png'),

('Клере', 2122, 3, 2, (select system.id from system where system.name = 'Хезе'), -660, -857, 'p2.png'),
('Напор', 8957, 2, 1, (select system.id from system where system.name = 'Хезе'), 842, -310, 'p8.png'),
('Абсент', 0, null, null, (select system.id from system where system.name = 'Хезе'), 1248, -579, 'p8.png'),
('Блогер', 0, null, null, (select system.id from system where system.name = 'Хезе'), -642, 16, 'p8.png'),
('Наусец', 0, null, null, (select system.id from system where system.name = 'Хезе'), 546, -571, 'p1.png'),

('Пекло', 5059, 3, 1, (select system.id from system where system.name = 'Таллот'), 714, 554, 'p5.png'),
('Чаевод', 0, null, null, (select system.id from system where system.name = 'Таллот'), -936, 46, 'p5.png'),
('Ноноза', 1684, 2, 1, (select system.id from system where system.name = 'Таллот'), 987, -1139, 'p7.png'),
('Тоддит', 4780, 2, 1, (select system.id from system where system.name = 'Таллот'), -565, -1225, 'p6.png'),

('Облов', 0, null, null, (select system.id from system where system.name = 'Ругулус'), -231, -98, 'p8.png'),
('Мятие', 9048, 3, 2, (select system.id from system where system.name = 'Ругулус'), 772, -173, 'p8.png'),
('Дачка', 5709, 1, 1, (select system.id from system where system.name = 'Ругулус'), -684, -134, 'p8.png'),
('Ежиха', 0, null, null, (select system.id from system where system.name = 'Ругулус'), -144, -983, 'p2.png'),

('Дурное', 4919, 3, 1, (select system.id from system where system.name = 'Гевер'), 625, -954, 'p1.png'),
('Оарион', 9742, 1, 2, (select system.id from system where system.name = 'Гевер'), -344, 85, 'p5.png'),
('Андрия', 1893, 2, 2, (select system.id from system where system.name = 'Гевер'), 103, 365, 'p8.png'),
('Ясенец', 8523, 1, 1, (select system.id from system where system.name = 'Гевер'), -443, 1069, 'p2.png'),

('Подрод', 6169, 3, 1, (select system.id from system where system.name = 'Наккар'), 1203, -591, 'p4.png'),
('Крайер', 4112, 3, 1, (select system.id from system where system.name = 'Наккар'), 705, -331, 'p4.png'),
('Воблер', 3844, 1, 2, (select system.id from system where system.name = 'Наккар'), -132, -659, 'p3.png'),

('Фронт', 9692, 1, 1, (select system.id from system where system.name = 'Селиостр'), 58, 981, 'p4.png'),
('Геллен', 0, null, null, (select system.id from system where system.name = 'Селиостр'), 531, -450, 'p8.png'),
('Форинт', 3378, 3, 2, (select system.id from system where system.name = 'Селиостр'), -139, 460, 'p4.png'),
('Лесище', 252, 2, 2, (select system.id from system where system.name = 'Селиостр'), 522, 852, 'p7.png'),

('Хилый', 544, 1, 2, (select system.id from system where system.name = 'Укфал'), 30, 637, 'p5.png'),
('Такель', 7546, 2, 2, (select system.id from system where system.name = 'Укфал'), -786, -1228, 'p1.png'),
('Ибогин', 4753, 2, 1, (select system.id from system where system.name = 'Укфал'), 179, 503, 'p6.png'),
('Менса', 6568, 1, 1, (select system.id from system where system.name = 'Укфал'), 248, 1013, 'p8.png'),
('Чаньго', 122, 1, 2, (select system.id from system where system.name = 'Укфал'), 1196, 1117, 'p2.png'),
('Венок', 756, 3, 2, (select system.id from system where system.name = 'Укфал'), -283, 800, 'p7.png'),

('Анурез', 0, null, null, (select system.id from system where system.name = 'Юфалли'), 1216, -491, 'p1.png'),
('Палики', 5099, 1, 1, (select system.id from system where system.name = 'Юфалли'), 1175, -79, 'p8.png'),
('Ускок', 962, 3, 1, (select system.id from system where system.name = 'Юфалли'), -798, 218, 'p7.png'),

('Кобия', 3132, 1, 2, (select system.id from system where system.name = 'Денеб'), -838, -644, 'p4.png'),
('Сорбит', 0, null, null, (select system.id from system where system.name = 'Денеб'), -527, -162, 'p6.png'),
('Могель', 0, null, null, (select system.id from system where system.name = 'Денеб'), -1230, 180, 'p7.png'),
('Нажим', 7582, 3, 2, (select system.id from system where system.name = 'Денеб'), 233, -1242, 'p5.png'),
('Веллон', 9576, 3, 1, (select system.id from system where system.name = 'Денеб'), 0, 466, 'p2.png'),

('Сенон', 2725, 3, 2, (select system.id from system where system.name = 'Атрия'), -1210, -963, 'p7.png'),
('Нерине', 0, null, null, (select system.id from system where system.name = 'Атрия'), -660, 145, 'p4.png'),
('Полдин', 230, 3, 1, (select system.id from system where system.name = 'Атрия'), 768, 548, 'p8.png'),

('Вгонка', 0, null, null, (select system.id from system where system.name = 'Фелгест'), 69, 55, 'p5.png'),
('Чиамба', 0, null, null, (select system.id from system where system.name = 'Фелгест'), -541, 652, 'p5.png'),
('Вещун', 9632, 2, 2, (select system.id from system where system.name = 'Фелгест'), 249, 774, 'p7.png'),
('Котище', 6632, 3, 1, (select system.id from system where system.name = 'Фелгест'), -249, 852, 'p8.png'),
('Бэнди', 0, null, null, (select system.id from system where system.name = 'Фелгест'), -621, 953, 'p7.png'),
('Латте', 7198, 2, 1, (select system.id from system where system.name = 'Фелгест'), -892, -641, 'p3.png'),

('Грабли', 7478, 2, 1, (select system.id from system where system.name = 'Завия'), -532, 1224, 'p7.png'),
('Аршин', 3893, 2, 1, (select system.id from system where system.name = 'Завия'), -766, -1275, 'p5.png'),
('Арабан', 0, null, null, (select system.id from system where system.name = 'Завия'), 1086, 306, 'p8.png'),
('Квагга', 0, null, null, (select system.id from system where system.name = 'Завия'), 114, -262, 'p8.png'),
('Петаом', 3734, 2, 2, (select system.id from system where system.name = 'Завия'), 1136, -73, 'p5.png'),
('Стринг', 0, null, null, (select system.id from system where system.name = 'Завия'), 1121, 581, 'p6.png'),

('Асура', 5503, 3, 1, (select system.id from system where system.name = 'Диадема'), 533, 471, 'p2.png'),
('Земец', 5012, 2, 2, (select system.id from system where system.name = 'Диадема'), -1138, -1041, 'p8.png'),
('Субаг', 7990, 1, 2, (select system.id from system where system.name = 'Диадема'), -468, -218, 'p8.png'),
('Жница', 8865, 2, 2, (select system.id from system where system.name = 'Диадема'), -1146, -757, 'p8.png'),
('Голак', 623, 3, 2, (select system.id from system where system.name = 'Диадема'), -1077, -197, 'p4.png'),
('Атопит', 0, null, null, (select system.id from system where system.name = 'Диадема'), -255, -831, 'p3.png'),

('Понит', 0, null, null, (select system.id from system where system.name = 'Маркаб'), -694, -1121, 'p6.png'),
('Дудук', 8699, 2, 2, (select system.id from system where system.name = 'Маркаб'), 858, -811, 'p6.png'),
('Щипец', 0, null, null, (select system.id from system where system.name = 'Маркаб'), 869, 376, 'p6.png'),
('Заюшка', 0, null, null, (select system.id from system where system.name = 'Маркаб'), -610, -1288, 'p1.png'),

('Хопеш', 0, null, null, (select system.id from system where system.name = 'Аркабе'), 1062, 923, 'p5.png'),
('Зевок', 7448, 2, 1, (select system.id from system where system.name = 'Аркабе'), -264, 470, 'p5.png'),
('Пифос', 0, null, null, (select system.id from system where system.name = 'Аркабе'), 412, 275, 'p2.png'),
('Биолит', 0, null, null, (select system.id from system where system.name = 'Аркабе'), 813, 1147, 'p7.png'),

('Папаха', 0, null, null, (select system.id from system where system.name = 'Канопус'), -1137, -764, 'p6.png'),
('Редкий', 4199, 1, 2, (select system.id from system where system.name = 'Канопус'), 471, 808, 'p8.png'),
('Подтёк', 6464, 1, 2, (select system.id from system where system.name = 'Канопус'), 204, -1030, 'p3.png'),
('Список', 96, 2, 1, (select system.id from system where system.name = 'Канопус'), -120, 519, 'p3.png'),
('Жатка', 0, null, null, (select system.id from system where system.name = 'Канопус'), -209, 329, 'p7.png'),

('Такка', 612, 1, 2, (select system.id from system where system.name = 'Сезмен'), 695, -1209, 'p3.png'),
('Армия', 2849, 1, 2, (select system.id from system where system.name = 'Сезмен'), -430, -135, 'p6.png'),
('Кекур', 2464, 1, 2, (select system.id from system where system.name = 'Сезмен'), 531, -486, 'p7.png'),
('Миссия', 7294, 2, 2, (select system.id from system where system.name = 'Сезмен'), -1030, 995, 'p3.png'),
('Разное', 3250, 3, 1, (select system.id from system where system.name = 'Сезмен'), -774, 986, 'p2.png'),
('Губной', 387, 2, 2, (select system.id from system where system.name = 'Сезмен'), 1137, 416, 'p2.png'),

('Офихт', 6814, 1, 2, (select system.id from system where system.name = 'Муррац'), -41, 1056, 'p4.png'),
('Бахта', 764, 2, 1, (select system.id from system where system.name = 'Муррац'), 226, 970, 'p6.png'),
('Колок', 0, null, null, (select system.id from system where system.name = 'Муррац'), -197, 411, 'p5.png'),

('Шкоты', 2327, 3, 1, (select system.id from system where system.name = 'Бетельгейзе'), -1089, -507, 'p8.png'),
('Галон', 3465, 2, 2, (select system.id from system where system.name = 'Бетельгейзе'), -1033, 1297, 'p6.png'),
('Вайма', 0, null, null, (select system.id from system where system.name = 'Бетельгейзе'), -7, -1271, 'p7.png'),
('Ларга', 1259, 3, 2, (select system.id from system where system.name = 'Бетельгейзе'), -131, 956, 'p6.png'),

('Телок', 8340, 2, 2, (select system.id from system where system.name = 'Кефрон'), -1218, -126, 'p3.png'),
('Шхоут', 8340, 2, 2, (select system.id from system where system.name = 'Кефрон'), -330, -282, 'p2.png'),
('Клиент', 0, null, null, (select system.id from system where system.name = 'Кефрон'), 990, 870, 'p7.png'),
('Комик', 7403, 1, 1, (select system.id from system where system.name = 'Кефрон'), 279, 804, 'p2.png'),

('Держак', 1265, 1, 2, (select system.id from system where system.name = 'Солнце'), 181, -1249, 'p6.png'),
('Хокку', 0, null, null, (select system.id from system where system.name = 'Солнце'), 814, -1140, 'p2.png'),
('Будра', 0, null, null, (select system.id from system where system.name = 'Солнце'), -215, 405, 'p2.png'),
('Серпий', 9225, 1, 2, (select system.id from system where system.name = 'Солнце'), -434, -138, 'p8.png'),
('Ирида', 0, null, null, (select system.id from system where system.name = 'Солнце'), -1244, 585, 'p7.png');


-------LIVING_RACES-------

insert into living_races(race_id, planet_id) values
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Омилит')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Омилит')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Омилит')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Омилит')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Омилит')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Атрий')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Прожог')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Прожог')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Бирка')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Купава')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Купава')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Купава')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Гусли')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Бекас')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Венед')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Венед')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Венед')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Венед')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Венед')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Твердо')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Клере')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Клере')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Клере')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Напор')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Напор')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Пекло')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Ноноза')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Тоддит')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Тоддит')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Мятие')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Дачка')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Дурное')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Оарион')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Оарион')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Оарион')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Оарион')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Андрия')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Андрия')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Андрия')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Андрия')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Ясенец')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Ясенец')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Ясенец')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Подрод')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Подрод')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Подрод')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Подрод')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Подрод')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Крайер')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Воблер')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Воблер')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Воблер')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Фронт')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Форинт')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Лесище')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Хилый')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Хилый')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Такель')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Ибогин')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Менса')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Чаньго')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Венок')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Палики')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Ускок')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Кобия')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Нажим')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Веллон')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Сенон')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Полдин')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Полдин')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Полдин')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Полдин')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Полдин')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Вещун')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Котище')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Латте')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Грабли')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Грабли')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Грабли')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Грабли')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Аршин')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Петаом')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Петаом')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Петаом')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Асура')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Земец')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Субаг')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Жница')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Голак')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Голак')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Голак')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Голак')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Дудук')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Зевок')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Зевок')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Редкий')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Подтёк')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Список')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Список')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Список')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Такка')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Армия')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Кекур')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Кекур')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Миссия')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Разное')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Губной')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Офихт')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Офихт')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Офихт')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Офихт')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Офихт')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Бахта')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Шкоты')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Галон')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Ларга')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Телок')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Шхоут')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Шхоут')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Комик')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Держак')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Серпий'));



insert into pilot(name, description, race_id, rating, owner, image) values
('Плиинор-Га', 'Created by BOT', (select id from race where race.name = 'Гаалец'), -69,(select id from username where username.login = 'BOT'), 'gaal4.png'),
('Ула Ган', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -6,(select id from username where username.login = 'BOT'), 'fei2.png'),
('Эдуард', 'Created by BOT', (select id from race where race.name = 'Человек'), -58,(select id from username where username.login = 'BOT'), 'human4.png'),
('То-Олак', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 53,(select id from username where username.login = 'BOT'), 'gaal2.png'),
('Экитармиссен', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -4,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Фа-Арлан', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 75,(select id from username where username.login = 'BOT'), 'gaal5.png'),
('Келлис', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 51,(select id from username where username.login = 'BOT'), 'gaal3.png'),
('Залос', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 7,(select id from username where username.login = 'BOT'), 'gaal2.png'),
('Леонардо', 'Created by BOT', (select id from race where race.name = 'Человек'), -95,(select id from username where username.login = 'BOT'), 'human1.png'),
('Алиций', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 43,(select id from username where username.login = 'BOT'), 'gaal2.png'),
('Йцухен', 'Created by BOT', (select id from race where race.name = 'Пеленг'), 22,(select id from username where username.login = 'BOT'), 'peleng4.png'),
('Смираан', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 17,(select id from username where username.login = 'BOT'), 'gaal5.png'),
('Лаоффик', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -96,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Финайла', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -36,(select id from username where username.login = 'BOT'), 'fei2.png'),
('Ралого', 'Created by BOT', (select id from race where race.name = 'Малок'), -13,(select id from username where username.login = 'BOT'), 'maloc5.png'),
('Царондо', 'Created by BOT', (select id from race where race.name = 'Пеленг'), 36,(select id from username where username.login = 'BOT'), 'peleng2.png'),
('Ролаакан', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 41,(select id from username where username.login = 'BOT'), 'gaal4.png'),
('Кучма Хан', 'Created by BOT', (select id from race where race.name = 'Человек'), 68,(select id from username where username.login = 'BOT'), 'human5.png'),
('Ульрих', 'Created by BOT', (select id from race where race.name = 'Человек'), 10,(select id from username where username.login = 'BOT'), 'human4.png'),
('Проббар', 'Created by BOT', (select id from race where race.name = 'Малок'), 20,(select id from username where username.login = 'BOT'), 'maloc1.png'),
('Дик', 'Created by BOT', (select id from race where race.name = 'Человек'), 46,(select id from username where username.login = 'BOT'), 'human1.png'),
('Илоса', 'Created by BOT', (select id from race where race.name = 'Гаалец'), -11,(select id from username where username.login = 'BOT'), 'gaal5.png'),
('Прирамо', 'Created by BOT', (select id from race where race.name = 'Гаалец'), -45,(select id from username where username.login = 'BOT'), 'gaal5.png'),
('Шак Мулда', 'Created by BOT', (select id from race where race.name = 'Человек'), 61,(select id from username where username.login = 'BOT'), 'human4.png'),
('Шоонари', 'Created by BOT', (select id from race where race.name = 'Гаалец'), -82,(select id from username where username.login = 'BOT'), 'gaal2.png'),
('Ахайа', 'Created by BOT', (select id from race where race.name = 'Человек'), -98,(select id from username where username.login = 'BOT'), 'human5.png'),
('Синклер', 'Created by BOT', (select id from race where race.name = 'Человек'), 74,(select id from username where username.login = 'BOT'), 'human2.png'),
('Элном Кара', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -74,(select id from username where username.login = 'BOT'), 'fei2.png'),
('Метилла', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -49,(select id from username where username.login = 'BOT'), 'fei5.png'),
('Данила', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -21,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Улла Исни', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 75,(select id from username where username.login = 'BOT'), 'fei5.png'),
('Гудареб', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -62,(select id from username where username.login = 'BOT'), 'peleng4.png'),
('Рах Цулан', 'Created by BOT', (select id from race where race.name = 'Человек'), -26,(select id from username where username.login = 'BOT'), 'human3.png'),
('Лука', 'Created by BOT', (select id from race where race.name = 'Человек'), -39,(select id from username where username.login = 'BOT'), 'human5.png'),
('Эрнан', 'Created by BOT', (select id from race where race.name = 'Человек'), 25,(select id from username where username.login = 'BOT'), 'human2.png'),
('Маза', 'Created by BOT', (select id from race where race.name = 'Человек'), 76,(select id from username where username.login = 'BOT'), 'human2.png'),
('Артелга', 'Created by BOT', (select id from race where race.name = 'Пеленг'), 31,(select id from username where username.login = 'BOT'), 'peleng4.png'),
('Чахратак', 'Created by BOT', (select id from race where race.name = 'Пеленг'), 11,(select id from username where username.login = 'BOT'), 'peleng2.png'),
('Моларбо', 'Created by BOT', (select id from race where race.name = 'Пеленг'), 29,(select id from username where username.login = 'BOT'), 'peleng2.png'),
('Олмилай', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -49,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Онкиар', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -65,(select id from username where username.login = 'BOT'), 'fei1.png'),
('Гааори', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 65,(select id from username where username.login = 'BOT'), 'gaal3.png'),
('Язилла Цукен', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -94,(select id from username where username.login = 'BOT'), 'peleng4.png'),
('Монтер', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -17,(select id from username where username.login = 'BOT'), 'peleng2.png'),
('Фейриаган', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 69,(select id from username where username.login = 'BOT'), 'fei4.png'),
('Сооламис', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 76,(select id from username where username.login = 'BOT'), 'gaal2.png'),
('Запецанец', 'Created by BOT', (select id from race where race.name = 'Человек'), 3,(select id from username where username.login = 'BOT'), 'human2.png'),
('Бооматли', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 34,(select id from username where username.login = 'BOT'), 'gaal2.png'),
('Грумандо', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -52,(select id from username where username.login = 'BOT'), 'peleng4.png'),
('Онаемлак', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -78,(select id from username where username.login = 'BOT'), 'fei5.png'),
('Дантар', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -83,(select id from username where username.login = 'BOT'), 'peleng2.png'),
('Белый', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -48,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Герхард', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -91,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Рорра-Аки', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 61,(select id from username where username.login = 'BOT'), 'gaal3.png'),
('Микита', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 90,(select id from username where username.login = 'BOT'), 'fei2.png'),
('Липецек', 'Created by BOT', (select id from race where race.name = 'Человек'), -45,(select id from username where username.login = 'BOT'), 'human1.png'),
('Петер', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -48,(select id from username where username.login = 'BOT'), 'fei5.png'),
('Коргар', 'Created by BOT', (select id from race where race.name = 'Пеленг'), 8,(select id from username where username.login = 'BOT'), 'peleng5.png'),
('Барогаб', 'Created by BOT', (select id from race where race.name = 'Пеленг'), 45,(select id from username where username.login = 'BOT'), 'peleng1.png'),
('Милианай', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 98,(select id from username where username.login = 'BOT'), 'fei3.png');


---------

insert into spaceship(name, spaceship_type_id, pilot_id, system_id, image) values
('Пиратский корабль Плиинор-Га', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Плиинор-Га'),22,'2GaalP.png'),
('Дипломатический корабль Ула Ган', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Ула Ган'),6,'2FeiL.png'),
('Пиратский корабль Эдуард', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Эдуард'),12,'2HumanP.png'),
('Корабль Рейнджера То-Олак', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'То-Олак'),10,'2GaalR.png'),
('Грузовой транспорт Экитармиссен', (select id from spaceship_type where spaceship_type.name = 'Грузовой транспорт'), (select id from pilot where pilot.name = 'Экитармиссен'),24,'2FeiW.png'),
('Корабль Рейнджера Фа-Арлан', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Фа-Арлан'),12,'2GaalR.png'),
('Корабль Рейнджера Келлис', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Келлис'),11,'2GaalR.png'),
('Грузовой транспорт Залос', (select id from spaceship_type where spaceship_type.name = 'Военный корабль'), (select id from pilot where pilot.name = 'Залос'),8,'2GaalL.png'),
('Пиратский корабль Леонардо', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Леонардо'),14,'2HumanP.png'),
('Корабль Рейнджера Алиций', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Алиций'),24,'2GaalR.png'),
('Военный корабль Йцухен', (select id from spaceship_type where spaceship_type.name = 'Военный корабль'), (select id from pilot where pilot.name = 'Йцухен'),21,'2PelengT.png'),
('Военный корабль Смираан', (select id from spaceship_type where spaceship_type.name = 'Грузовой транспорт'), (select id from pilot where pilot.name = 'Смираан'),20,'2GaalD.png'),
('Пиратский корабль Лаоффик', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Лаоффик'),22,'2FeiP.png'),
('Пиратский корабль Финайла', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Финайла'),23,'2FeiP.png'),
('Дипломатический корабль Ралого', (select id from spaceship_type where spaceship_type.name = 'Дипломатический корабль'), (select id from pilot where pilot.name = 'Ралого'),3,'2MalocL.png'),
('Военный корабль Царондо', (select id from spaceship_type where spaceship_type.name = 'Дипломатический корабль'), (select id from pilot where pilot.name = 'Царондо'),21,'2PelengD.png'),
('Корабль Рейнджера Ролаакан', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Ролаакан'),2,'2GaalR.png'),
('Корабль Рейнджера Кучма Хан', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Кучма Хан'),18,'2HumanR.png'),
('Военный корабль Ульрих', (select id from spaceship_type where spaceship_type.name = 'Дипломатический корабль'), (select id from pilot where pilot.name = 'Ульрих'),4,'2HumanD.png'),
('Военный корабль Проббар', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Проббар'),23,'2MalocT.png'),
('Корабль Рейнджера Дик', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Дик'),18,'2HumanR.png'),
('Грузовой транспорт Илоса', (select id from spaceship_type where spaceship_type.name = 'Грузовой транспорт'), (select id from pilot where pilot.name = 'Илоса'),18,'2GaalL.png'),
('Пиратский корабль Прирамо', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Прирамо'),5,'2GaalP.png'),
('Корабль Рейнджера Шак Мулда', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Шак Мулда'),11,'2HumanR.png'),
('Пиратский корабль Шоонари', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Шоонари'),19,'2GaalP.png'),
('Пиратский корабль Ахайа', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Ахайа'),18,'2HumanP.png'),
('Корабль Рейнджера Синклер', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Синклер'),25,'2HumanR.png'),
('Пиратский корабль Элном Кара', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Элном Кара'),19,'2FeiP.png'),
('Пиратский корабль Метилла', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Метилла'),18,'2FeiP.png'),
('Пиратский корабль Данила', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Данила'),5,'2FeiP.png'),
('Корабль Рейнджера Улла Исни', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Улла Исни'),4,'2FeiR.png'),
('Пиратский корабль Гудареб', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Гудареб'),10,'2PelengP.png'),
('Пиратский корабль Рах Цулан', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Рах Цулан'),1,'2HumanP.png'),
('Пиратский корабль Лука', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Лука'),15,'2HumanP.png'),
('Грузовой транспорт Эрнан', (select id from spaceship_type where spaceship_type.name = 'Военный корабль'), (select id from pilot where pilot.name = 'Эрнан'),19,'2HumanT.png'),
('Корабль Рейнджера Маза', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Маза'),10,'2HumanR.png'),
('Грузовой транспорт Артелга', (select id from spaceship_type where spaceship_type.name = 'Грузовой транспорт'), (select id from pilot where pilot.name = 'Артелга'),13,'2PelengT.png'),
('Дипломатический корабль Чахратак', (select id from spaceship_type where spaceship_type.name = 'Дипломатический корабль'), (select id from pilot where pilot.name = 'Чахратак'),5,'2PelengD.png'),
('Пассажирский Лайнер Моларбо', (select id from spaceship_type where spaceship_type.name = 'Дипломатический корабль'), (select id from pilot where pilot.name = 'Моларбо'),5,'2PelengD.png'),
('Пиратский корабль Олмилай', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Олмилай'),22,'2FeiP.png'),
('Пиратский корабль Онкиар', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Онкиар'),17,'2FeiP.png'),
('Корабль Рейнджера Гааори', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Гааори'),10,'2GaalR.png'),
('Пиратский корабль Язилла Цукен', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Язилла Цукен'),14,'2PelengP.png'),
('Пассажирский Лайнер Монтер', (select id from spaceship_type where spaceship_type.name = 'Дипломатический корабль'), (select id from pilot where pilot.name = 'Монтер'),15,'2PelengW.png'),
('Корабль Рейнджера Фейриаган', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Фейриаган'),24,'2FeiR.png'),
('Корабль Рейнджера Сооламис', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Сооламис'),5,'2GaalR.png'),
('Дипломатический корабль Запецанец', (select id from spaceship_type where spaceship_type.name = 'Военный корабль'), (select id from pilot where pilot.name = 'Запецанец'),5,'2HumanD.png'),
('Грузовой транспорт Бооматли', (select id from spaceship_type where spaceship_type.name = 'Грузовой транспорт'), (select id from pilot where pilot.name = 'Бооматли'),4,'2GaalD.png'),
('Пиратский корабль Грумандо', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Грумандо'),23,'2PelengP.png'),
('Пиратский корабль Онаемлак', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Онаемлак'),5,'2FeiP.png'),
('Пиратский корабль Дантар', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Дантар'),7,'2PelengP.png'),
('Пиратский корабль Белый', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Белый'),5,'2FeiP.png'),
('Пиратский корабль Герхард', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Герхард'),25,'2FeiP.png'),
('Корабль Рейнджера Рорра-Аки', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Рорра-Аки'),25,'2GaalR.png'),
('Флагман Микита', (select id from spaceship_type where spaceship_type.name = 'Флагман'), (select id from pilot where pilot.name = 'Микита'),2,'2FeiBW.png'),
('Пиратский корабль Липецек', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Липецек'),8,'2HumanP.png'),
('Пиратский корабль Петер', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Петер'),10,'2FeiP.png'),
('Дипломатический корабль Коргар', (select id from spaceship_type where spaceship_type.name = 'Грузовой транспорт'), (select id from pilot where pilot.name = 'Коргар'),7,'2PelengT.png'),
('Корабль Рейнджера Барогаб', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Барогаб'),7,'2PelengR.png'),
('Флагман Милианай', (select id from spaceship_type where spaceship_type.name = 'Флагман'), (select id from pilot where pilot.name = 'Милианай'),1,'2FeiBW.png');

insert into spacebase(name, spacebase_type_id, system_id)
values ('Пьяный корсар',
        (select id from spacebase_type where spacebase_type.name = 'Черный рынок'),
        (select id from system where system.name = 'Таллот')),
       ('Костоправ',
        (select id from spacebase_type where spacebase_type.name = 'Медицинский центр'),
        (select id from system where system.name = 'Солнце')),
       ('Террор',
        (select id from spacebase_type where spacebase_type.name = 'Черный рынок'),
        (select id from system where system.name = 'Шеат')),
       ('Доминион',
        (select id from spacebase_type where spacebase_type.name = 'Доминион'),
        (select id from system where system.name = 'Денеб')),
       ('Альфа',
        (select id from spacebase_type where spacebase_type.name = 'Военная база'),
        (select id from system where system.name = 'Фелгест')),
       ('Мечтатель',
        (select id from spacebase_type where spacebase_type.name = 'Центр рейнджеров'),
        (select id from system where system.name = 'Диадема')),
       ('Квантум',
        (select id from spacebase_type where spacebase_type.name = 'Научная станция'),
        (select id from system where system.name = 'Бетельгейзе')),
       ('Эконом',
        (select id from spacebase_type where spacebase_type.name = 'Бизнес-центр'),
        (select id from system where system.name = 'Таллот'))
;

insert into action_type
    (name, action_impact)
values ('Нападение на торговое судно', -4),
       ('Помощь терпящему крушение мирному кораблю', +2);


insert into action
    (action_description, pilot_id, action_type_id)
values ('Было совершено ограбление торгового судна. Обошлось без жертв.',
        1,
        (select id from action_type where action_type.name = 'Нападение на торговое судно'));

insert into action_type
(name, action_impact)
values ('Сделать очень плохо', -3),
       ('Сделать  плохо', -1),
       ('Сделать нормально', 0),
       ('Сделать хорошо', 1),
       ('Сделать очень хорошо', 3);

insert into action
(action_description, pilot_id, action_type_id)
values ('Было совершено ограбление торгового судна. Обошлось без жертв.',
        2,
        (select id from action_type where action_type.name = 'Нападение на торговое судно'));
