insert into username
values (default, 'BOT', 'LOGIN');

insert into spaceship_type
values (default,
        'Грузовой транспорт',
        'Медленный, бронированный и грузоподъёмный. Слабое вооружения.'),
       (default,
        'Дипломатический корабль',
        'Быстрый, броннированный, с неплохим вооружением. Используется для дипломатический миссий.'),
       (default,
        'Пассажирский Лайнер',
        'Среднескоростной и бронированный, служит для транспортировки пассажиров. Слабое вооружения.'),
       (default,
        'Военный корабль',
        'корабль средней скорости, хорошее вооружение, хорошая броня.'),
       (default,
        'Пиратский корабль',
        'Быстрый корабль, среднее вооружение, но слабая защита корпуса. Лучшее что' ||
        ' можно было собрать из космичекого мусора'),
       (default,
        'Корабль Рейнджера',
        'Корабль средней скорости, хорошее вооружение и броня.'),
       (default,
        'Флагман',
        'Является крупным военным кораблём. Крайне медлительный, но имеет прекрасную прочность' ||
        'корпуса и передовое вооружение');

insert into spacebase_type
values (default,
        'Медицинский центр',
        'Медицинский центр - место где можно подправить руки, ноги и другие конечности.',
        'MB.png',
        -32,
        100),
       (default,
        'Бизнес-центр',
        'Космический банк. Ну что о нём можно сказать... Работает как любой другой банк.',
        'BC.png',
        0,
        100),
       (default,
        'Военная база',
        'Космическая военная база. О ней мало какой-либо информации ввиду её секретности.',
        'WB.png',
        75,
        100),
       (default,
        'Черный рынок',
        'Место скопления воров и мошенников. Здесь можно прибрести не совсем законные вещи.',
        'PB.png',
        -100,
        100),
       (default,
        'Научная станция',
        'Научная станция - отличное место для приобретения передовых технологий.',
        'SB.png',
        20,
        100),
       (default, 'Доминион',
        'Удивительно, но у пиратского союза также есть своя космическая база. Благодаря своей ' ||
        'удивительной технологии менять своё месторасположение в галактике, на космическую базу Доминион' ||
        ' ещё никому не удалось напасть.',
        'Domin.png',
        -100,
        -25),
       (default,
        'Центр рейнджеров',
        'Проводят классификацию рейнджеров. Информируют планеты о деятельности тех или иных рейнджеров',
        'RB.png',
        25,
        100);

insert into politics
values (default,
        'Абсолютная монархия',
        'Форма правления или государственного устройства, при котором пост официального главой государства закреплён за монархом.'),
       (default,
        'Демократия',
        'Форма правления, при которой народ имеет право выбирать своих правящих законодателей'),
       (default,
        'Анархия',
        'Здесь нет власти, правил или законов. Однако слабые все равно вынуждены подчиняться сильным'),
       (default,
        'Республика',
        'Форма государственного правления, при которой все органы государственной власти либо избираются на определённый срок,' ||
        ' либо формируются общенациональными представительными учреждениями (например, парламентом), а граждане обладают личными и политическими правами.');

insert into economics
values (default, 'Аграрная', 'Преобладает сельское хозяйство.'),
       (default, 'Индустриальная', 'Преобладает промышленность с гибкими динамичными структурами.'),
       (default, 'Смешанная', 'Развитие аграрной и индустриальной промышленностей идёт равномено.');

insert into race
values (default, 'Человек', 'Две руки, две ноги - на макаку похож.'),
       (default, 'Фэяне', 'Раса гуманоидов-гермафродитов с большим мозгом и фасеточными глазами.'),
       (default, 'Малок',
        'Крупные, мощного телосложения гуманоиды. Для них характерна огромная физическая сила, ' || 'выносливость, ' ||
        'Высокая сопротивляемость природным факторам, не слишком активная мыслительная деятельность.'),
       (default, 'Гаалец',
        'Гуманоиды, тысячелетиями модифицирующие свою биологическую форму путем генетических модификаций эмбрионов.'),
       (default, 'Пеленг',
        'Относятся к виду жаброшеих амфибий. Этот вид существ одинаково хорошо приспособлен для обитания как в жидкой среде, так и на суше.');


-------SECTOR---------
insert into sector(name) values
('Атланта'),
('Фаави'),
('Таолис'),
('Нароби'),
('Реггет'),
('Эльта'),
('Карагон');

-------SYSTEMS---------
insert into system(name, sector_id, image) values
('Витта Прайонис', (select sector.id from sector where sector.name = 'Атланта'), 's5.png'),
('Шеат', (select sector.id from sector where sector.name = 'Атланта'), 's4.png'),
('Краа', (select sector.id from sector where sector.name = 'Атланта'), 's3.png'),
('Тураис', (select sector.id from sector where sector.name = 'Атланта'), 's8.png'),

('Хезе', (select sector.id from sector where sector.name = 'Фаави'), 's5.png'),
('Таллот', (select sector.id from sector where sector.name = 'Фаави'), 's8.png'),
('Ругулус', (select sector.id from sector where sector.name = 'Фаави'), 's7.png'),

('Гевер', (select sector.id from sector where sector.name = 'Таолис'), 's7.png'),
('Наккар', (select sector.id from sector where sector.name = 'Таолис'), 's3.png'),
('Селиостр', (select sector.id from sector where sector.name = 'Таолис'), 's3.png'),

('Укфал', (select sector.id from sector where sector.name = 'Нароби'), 's5.png'),
('Юфалли', (select sector.id from sector where sector.name = 'Нароби'), 's2.png'),
('Денеб', (select sector.id from sector where sector.name = 'Нароби'), 's4.png'),
('Атрия', (select sector.id from sector where sector.name = 'Нароби'), 's5.png'),

('Фелгест', (select sector.id from sector where sector.name = 'Реггет'), 's2.png'),
('Завия', (select sector.id from sector where sector.name = 'Реггет'), 's6.png'),
('Диадема', (select sector.id from sector where sector.name = 'Реггет'), 's3.png'),

('Маркаб', (select sector.id from sector where sector.name = 'Эльта'), 's5.png'),
('Аркабе', (select sector.id from sector where sector.name = 'Эльта'), 's10.png'),
('Канопус', (select sector.id from sector where sector.name = 'Эльта'), 's3.png'),
('Сезмен', (select sector.id from sector where sector.name = 'Эльта'), 's14.png'),
('Муррац', (select sector.id from sector where sector.name = 'Эльта'), 's4.png'),

('Бетельгейзе', (select sector.id from sector where sector.name = 'Карагон'), 's5.png'),
('Кефрон', (select sector.id from sector where sector.name = 'Карагон'), 's6.png'),
('Солнце', (select sector.id from sector where sector.name = 'Карагон'), 's6.png');


-------PLANETS-------

insert into planet(name, citizens, politics_id, economics_id, system_id, coord_x, coord_y, image) values
('Невод', 0, null, null, (select system.id from system where system.name = 'Витта Прайонис'), 1140, 796, 'p5.png'),
('Омилит', 1703, 3, 1, (select system.id from system where system.name = 'Витта Прайонис'), -360, -233, 'p7.png'),
('Атрий', 2325, 3, 1, (select system.id from system where system.name = 'Витта Прайонис'), -1264, -735, 'p7.png'),
('Прожог', 30, 3, 2, (select system.id from system where system.name = 'Витта Прайонис'), 307, 100, 'p3.png'),

('Клёцка', 0, null, null, (select system.id from system where system.name = 'Шеат'), 157, 521, 'p3.png'),
('Бирка', 5110, 2, 1, (select system.id from system where system.name = 'Шеат'), 1283, 138, 'p2.png'),
('Купава', 9977, 1, 1, (select system.id from system where system.name = 'Шеат'), 542, 955, 'p6.png'),

('Гусли', 2328, 1, 2, (select system.id from system where system.name = 'Краа'), 586, -790, 'p8.png'),
('Бекас', 8034, 1, 2, (select system.id from system where system.name = 'Краа'), -196, -601, 'p4.png'),
('Венед', 4987, 1, 1, (select system.id from system where system.name = 'Краа'), 317, 115, 'p7.png'),
('Твердо', 1871, 3, 1, (select system.id from system where system.name = 'Краа'), 1183, 1281, 'p4.png'),
('Кайчи', 0, null, null, (select system.id from system where system.name = 'Краа'), -468, 1060, 'p5.png'),
('Заплыв', 0, null, null, (select system.id from system where system.name = 'Краа'), 291, 768, 'p2.png'),

('Тагиш', 0, null, null, (select system.id from system where system.name = 'Тураис'), -51, -872, 'p3.png'),
('Накол', 0, null, null, (select system.id from system where system.name = 'Тураис'), 862, 482, 'p3.png'),
('Завязь', 0, null, null, (select system.id from system where system.name = 'Тураис'), 1265, 309, 'p4.png'),

('Клере', 2122, 3, 2, (select system.id from system where system.name = 'Хезе'), -660, -857, 'p2.png'),
('Напор', 8957, 2, 1, (select system.id from system where system.name = 'Хезе'), 842, -310, 'p8.png'),
('Абсент', 0, null, null, (select system.id from system where system.name = 'Хезе'), 1248, -579, 'p8.png'),
('Блогер', 0, null, null, (select system.id from system where system.name = 'Хезе'), -642, 16, 'p8.png'),
('Наусец', 0, null, null, (select system.id from system where system.name = 'Хезе'), 546, -571, 'p1.png'),

('Пекло', 5059, 3, 1, (select system.id from system where system.name = 'Таллот'), 714, 554, 'p5.png'),
('Чаевод', 0, null, null, (select system.id from system where system.name = 'Таллот'), -936, 46, 'p5.png'),
('Ноноза', 1684, 2, 1, (select system.id from system where system.name = 'Таллот'), 987, -1139, 'p7.png'),
('Тоддит', 4780, 2, 1, (select system.id from system where system.name = 'Таллот'), -565, -1225, 'p6.png'),

('Облов', 0, null, null, (select system.id from system where system.name = 'Ругулус'), -231, -98, 'p8.png'),
('Мятие', 9048, 3, 2, (select system.id from system where system.name = 'Ругулус'), 772, -173, 'p8.png'),
('Дачка', 5709, 1, 1, (select system.id from system where system.name = 'Ругулус'), -684, -134, 'p8.png'),
('Ежиха', 0, null, null, (select system.id from system where system.name = 'Ругулус'), -144, -983, 'p2.png'),

('Дурное', 4919, 3, 1, (select system.id from system where system.name = 'Гевер'), 625, -954, 'p1.png'),
('Оарион', 9742, 1, 2, (select system.id from system where system.name = 'Гевер'), -344, 85, 'p5.png'),
('Андрия', 1893, 2, 2, (select system.id from system where system.name = 'Гевер'), 103, 365, 'p8.png'),
('Ясенец', 8523, 1, 1, (select system.id from system where system.name = 'Гевер'), -443, 1069, 'p2.png'),

('Подрод', 6169, 3, 1, (select system.id from system where system.name = 'Наккар'), 1203, -591, 'p4.png'),
('Крайер', 4112, 3, 1, (select system.id from system where system.name = 'Наккар'), 705, -331, 'p4.png'),
('Воблер', 3844, 1, 2, (select system.id from system where system.name = 'Наккар'), -132, -659, 'p3.png'),

('Фронт', 9692, 1, 1, (select system.id from system where system.name = 'Селиостр'), 58, 981, 'p4.png'),
('Геллен', 0, null, null, (select system.id from system where system.name = 'Селиостр'), 531, -450, 'p8.png'),
('Форинт', 3378, 3, 2, (select system.id from system where system.name = 'Селиостр'), -139, 460, 'p4.png'),
('Лесище', 252, 2, 2, (select system.id from system where system.name = 'Селиостр'), 522, 852, 'p7.png'),

('Хилый', 544, 1, 2, (select system.id from system where system.name = 'Укфал'), 30, 637, 'p5.png'),
('Такель', 7546, 2, 2, (select system.id from system where system.name = 'Укфал'), -786, -1228, 'p1.png'),
('Ибогин', 4753, 2, 1, (select system.id from system where system.name = 'Укфал'), 179, 503, 'p6.png'),
('Менса', 6568, 1, 1, (select system.id from system where system.name = 'Укфал'), 248, 1013, 'p8.png'),
('Чаньго', 122, 1, 2, (select system.id from system where system.name = 'Укфал'), 1196, 1117, 'p2.png'),
('Венок', 756, 3, 2, (select system.id from system where system.name = 'Укфал'), -283, 800, 'p7.png'),

('Анурез', 0, null, null, (select system.id from system where system.name = 'Юфалли'), 1216, -491, 'p1.png'),
('Палики', 5099, 1, 1, (select system.id from system where system.name = 'Юфалли'), 1175, -79, 'p8.png'),
('Ускок', 962, 3, 1, (select system.id from system where system.name = 'Юфалли'), -798, 218, 'p7.png'),

('Кобия', 3132, 1, 2, (select system.id from system where system.name = 'Денеб'), -838, -644, 'p4.png'),
('Сорбит', 0, null, null, (select system.id from system where system.name = 'Денеб'), -527, -162, 'p6.png'),
('Могель', 0, null, null, (select system.id from system where system.name = 'Денеб'), -1230, 180, 'p7.png'),
('Нажим', 7582, 3, 2, (select system.id from system where system.name = 'Денеб'), 233, -1242, 'p5.png'),
('Веллон', 9576, 3, 1, (select system.id from system where system.name = 'Денеб'), 0, 466, 'p2.png'),

('Сенон', 2725, 3, 2, (select system.id from system where system.name = 'Атрия'), -1210, -963, 'p7.png'),
('Нерине', 0, null, null, (select system.id from system where system.name = 'Атрия'), -660, 145, 'p4.png'),
('Полдин', 230, 3, 1, (select system.id from system where system.name = 'Атрия'), 768, 548, 'p8.png'),

('Вгонка', 0, null, null, (select system.id from system where system.name = 'Фелгест'), 69, 54, 'p5.png'),
('Чиамба', 0, null, null, (select system.id from system where system.name = 'Фелгест'), -541, 652, 'p5.png'),
('Вещун', 9632, 2, 2, (select system.id from system where system.name = 'Фелгест'), 249, 774, 'p7.png'),
('Котище', 6632, 3, 1, (select system.id from system where system.name = 'Фелгест'), -249, 852, 'p8.png'),
('Бэнди', 0, null, null, (select system.id from system where system.name = 'Фелгест'), -621, 953, 'p7.png'),
('Латте', 7198, 2, 1, (select system.id from system where system.name = 'Фелгест'), -892, -641, 'p3.png'),

('Грабли', 7478, 2, 1, (select system.id from system where system.name = 'Завия'), -532, 1224, 'p7.png'),
('Аршин', 3893, 2, 1, (select system.id from system where system.name = 'Завия'), -766, -1275, 'p5.png'),
('Арабан', 0, null, null, (select system.id from system where system.name = 'Завия'), 1086, 306, 'p8.png'),
('Квагга', 0, null, null, (select system.id from system where system.name = 'Завия'), 114, -262, 'p8.png'),
('Петаом', 3734, 2, 2, (select system.id from system where system.name = 'Завия'), 1136, -73, 'p5.png'),
('Стринг', 0, null, null, (select system.id from system where system.name = 'Завия'), 1121, 581, 'p6.png'),

('Асура', 5503, 3, 1, (select system.id from system where system.name = 'Диадема'), 533, 471, 'p2.png'),
('Земец', 5012, 2, 2, (select system.id from system where system.name = 'Диадема'), -1138, -1041, 'p8.png'),
('Субаг', 7990, 1, 2, (select system.id from system where system.name = 'Диадема'), -468, -218, 'p8.png'),
('Жница', 8865, 2, 2, (select system.id from system where system.name = 'Диадема'), -1146, -757, 'p8.png'),
('Голак', 623, 3, 2, (select system.id from system where system.name = 'Диадема'), -1077, -197, 'p4.png'),
('Атопит', 0, null, null, (select system.id from system where system.name = 'Диадема'), -255, -831, 'p3.png'),

('Понит', 0, null, null, (select system.id from system where system.name = 'Маркаб'), -694, -1121, 'p6.png'),
('Дудук', 8699, 2, 2, (select system.id from system where system.name = 'Маркаб'), 858, -811, 'p6.png'),
('Щипец', 0, null, null, (select system.id from system where system.name = 'Маркаб'), 869, 376, 'p6.png'),
('Заюшка', 0, null, null, (select system.id from system where system.name = 'Маркаб'), -610, -1288, 'p1.png'),

('Хопеш', 0, null, null, (select system.id from system where system.name = 'Аркабе'), 1062, 923, 'p5.png'),
('Зевок', 7448, 2, 1, (select system.id from system where system.name = 'Аркабе'), -264, 470, 'p5.png'),
('Пифос', 0, null, null, (select system.id from system where system.name = 'Аркабе'), 412, 275, 'p2.png'),
('Биолит', 0, null, null, (select system.id from system where system.name = 'Аркабе'), 813, 1147, 'p7.png'),

('Папаха', 0, null, null, (select system.id from system where system.name = 'Канопус'), -1137, -764, 'p6.png'),
('Редкий', 4199, 1, 2, (select system.id from system where system.name = 'Канопус'), 471, 808, 'p8.png'),
('Подтёк', 6464, 1, 2, (select system.id from system where system.name = 'Канопус'), 204, -1030, 'p3.png'),
('Список', 96, 2, 1, (select system.id from system where system.name = 'Канопус'), -120, 519, 'p3.png'),
('Жатка', 0, null, null, (select system.id from system where system.name = 'Канопус'), -209, 329, 'p7.png'),

('Такка', 612, 1, 2, (select system.id from system where system.name = 'Сезмен'), 695, -1209, 'p3.png'),
('Армия', 2849, 1, 2, (select system.id from system where system.name = 'Сезмен'), -430, -135, 'p6.png'),
('Кекур', 2464, 1, 2, (select system.id from system where system.name = 'Сезмен'), 531, -486, 'p7.png'),
('Миссия', 7294, 2, 2, (select system.id from system where system.name = 'Сезмен'), -1030, 995, 'p3.png'),
('Разное', 3250, 3, 1, (select system.id from system where system.name = 'Сезмен'), -774, 986, 'p2.png'),
('Губной', 387, 2, 2, (select system.id from system where system.name = 'Сезмен'), 1137, 416, 'p2.png'),

('Офихт', 6814, 1, 2, (select system.id from system where system.name = 'Муррац'), -41, 1056, 'p4.png'),
('Бахта', 764, 2, 1, (select system.id from system where system.name = 'Муррац'), 226, 970, 'p6.png'),
('Колок', 0, null, null, (select system.id from system where system.name = 'Муррац'), -197, 411, 'p5.png'),

('Шкоты', 2327, 3, 1, (select system.id from system where system.name = 'Бетельгейзе'), -1089, -507, 'p8.png'),
('Галон', 3465, 2, 2, (select system.id from system where system.name = 'Бетельгейзе'), -1033, 1297, 'p6.png'),
('Вайма', 0, null, null, (select system.id from system where system.name = 'Бетельгейзе'), -7, -1271, 'p7.png'),
('Ларга', 1259, 3, 2, (select system.id from system where system.name = 'Бетельгейзе'), -131, 956, 'p6.png'),

('Телок', 8340, 2, 2, (select system.id from system where system.name = 'Кефрон'), -1218, -126, 'p3.png'),
('Шхоут', 764, 2, 1, (select system.id from system where system.name = 'Кефрон'), -330, -282, 'p2.png'),
('Клиент', 0, null, null, (select system.id from system where system.name = 'Кефрон'), 990, 870, 'p7.png'),
('Комик', 7403, 1, 1, (select system.id from system where system.name = 'Кефрон'), 279, 804, 'p2.png'),

('Меркурий', 1265, 1, 2, (select system.id from system where system.name = 'Солнце'), 181, -1249, 'solar/mercury.png'),
('Венера', 1265, 1, 2, (select system.id from system where system.name = 'Солнце'), 814, -1140, 'solar/venus.png'),
('Земля', 8340, 2, 2, (select system.id from system where system.name = 'Солнце'), -215, 405, 'solar/earth.png'),
('Марс', 387, 2, 2, (select system.id from system where system.name = 'Солнце'), -434, -138, 'solar/mars.png'),
('Юпитер', 0, null, null, (select system.id from system where system.name = 'Солнце'), -1244, 585, 'solar/jupiter.png'),
('Сатурн', 0, null, null, (select system.id from system where system.name = 'Солнце'), -330, -282, 'solar/saturn.png'),
('Уран', 0, null, null, (select system.id from system where system.name = 'Солнце'), -1033, 1297, 'solar/uranus.png'),
('Нептун', 0, null, null, (select system.id from system where system.name = 'Солнце'), 531, -486, 'solar/neptune.png');


-------LIVING_RACES-------

insert into living_races(race_id, planet_id) values
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Омилит')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Омилит')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Омилит')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Омилит')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Омилит')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Атрий')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Прожог')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Прожог')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Бирка')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Купава')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Купава')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Купава')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Гусли')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Бекас')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Венед')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Венед')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Венед')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Венед')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Венед')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Твердо')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Клере')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Клере')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Клере')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Напор')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Напор')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Пекло')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Ноноза')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Тоддит')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Тоддит')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Мятие')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Дачка')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Дурное')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Оарион')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Оарион')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Оарион')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Оарион')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Андрия')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Андрия')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Андрия')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Андрия')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Ясенец')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Ясенец')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Ясенец')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Подрод')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Подрод')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Подрод')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Подрод')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Подрод')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Крайер')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Воблер')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Воблер')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Воблер')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Фронт')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Форинт')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Лесище')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Хилый')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Хилый')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Такель')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Ибогин')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Менса')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Чаньго')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Венок')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Палики')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Ускок')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Кобия')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Нажим')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Веллон')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Сенон')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Полдин')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Полдин')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Полдин')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Полдин')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Полдин')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Вещун')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Котище')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Латте')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Грабли')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Грабли')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Грабли')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Грабли')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Аршин')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Петаом')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Петаом')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Петаом')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Асура')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Земец')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Субаг')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Жница')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Голак')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Голак')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Голак')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Голак')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Дудук')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Зевок')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Зевок')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Редкий')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Подтёк')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Список')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Список')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Список')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Такка')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Армия')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Кекур')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Кекур')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Миссия')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Разное')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Губной')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Офихт')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Офихт')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Офихт')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Офихт')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Офихт')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Бахта')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Шкоты')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Галон')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Ларга')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Телок')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Шхоут')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Шхоут')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Комик')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Венера')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Земля')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Марс'));




insert into pilot(name, description, race_id, rating, owner, image) values
('Аргатру', 'Created by BOT', (select id from race where race.name = 'Малок'), 10,(select id from username where username.login = 'BOT'), 'maloc3.png'),
('Гааори', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 37,(select id from username where username.login = 'BOT'), 'gaal4.png'),
('Леестак', 'Created by BOT', (select id from race where race.name = 'Гаалец'), -71,(select id from username where username.login = 'BOT'), 'gaal2.png'),
('Ашпарака', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -90,(select id from username where username.login = 'BOT'), 'peleng4.png'),
('Рорра-Аки', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 22,(select id from username where username.login = 'BOT'), 'gaal2.png'),
('Моларбо', 'Created by BOT', (select id from race where race.name = 'Малок'), -19,(select id from username where username.login = 'BOT'), 'maloc4.png'),
('Раноялми', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -41,(select id from username where username.login = 'BOT'), 'fei4.png'),
('Гроомак', 'Created by BOT', (select id from race where race.name = 'Гаалец'), -52,(select id from username where username.login = 'BOT'), 'gaal3.png'),
('Урааган', 'Created by BOT', (select id from race where race.name = 'Гаалец'), -56,(select id from username where username.login = 'BOT'), 'gaal3.png'),
('То-Олак', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 30,(select id from username where username.login = 'BOT'), 'gaal2.png'),
('Метилла', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 52,(select id from username where username.login = 'BOT'), 'fei4.png'),
('Лошашка', 'Created by BOT', (select id from race where race.name = 'Пеленг'), 29,(select id from username where username.login = 'BOT'), 'peleng1.png'),
('Артелга', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -8,(select id from username where username.login = 'BOT'), 'peleng1.png'),
('Зерогуд', 'Created by BOT', (select id from race where race.name = 'Малок'), -19,(select id from username where username.login = 'BOT'), 'maloc4.png'),
('Саб', 'Created by BOT', (select id from race where race.name = 'Человек'), -6,(select id from username where username.login = 'BOT'), 'human1.png'),
('Келлис', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 31,(select id from username where username.login = 'BOT'), 'gaal1.png'),
('Ошира Бен', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -47,(select id from username where username.login = 'BOT'), 'peleng4.png'),
('Лаки Хан', 'Created by BOT', (select id from race where race.name = 'Пеленг'), 29,(select id from username where username.login = 'BOT'), 'peleng2.png'),
('Лианарик', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -48,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Келобар', 'Created by BOT', (select id from race where race.name = 'Малок'), 75,(select id from username where username.login = 'BOT'), 'maloc4.png'),
('Цапиль', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -27,(select id from username where username.login = 'BOT'), 'peleng3.png'),
('Онаемлак', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -83,(select id from username where username.login = 'BOT'), 'fei2.png'),
('Элеомис', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 10,(select id from username where username.login = 'BOT'), 'fei2.png'),
('Прооглин', 'Created by BOT', (select id from race where race.name = 'Гаалец'), -19,(select id from username where username.login = 'BOT'), 'gaal1.png'),
('Кучма Хан', 'Created by BOT', (select id from race where race.name = 'Человек'), -2,(select id from username where username.login = 'BOT'), 'human2.png'),
('Константин', 'Created by BOT', (select id from race where race.name = 'Человек'), 95,(select id from username where username.login = 'BOT'), 'human1.png'),
('Тандрон', 'Created by BOT', (select id from race where race.name = 'Малок'), 4,(select id from username where username.login = 'BOT'), 'maloc2.png'),
('Умта Уоллис', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -44,(select id from username where username.login = 'BOT'), 'fei2.png'),
('Лаоффик', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 46,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Илик', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -32,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Рийомайцах', 'Created by BOT', (select id from race where race.name = 'Пеленг'), 19,(select id from username where username.login = 'BOT'), 'peleng5.png'),
('Удондер', 'Created by BOT', (select id from race where race.name = 'Малок'), -92,(select id from username where username.login = 'BOT'), 'maloc4.png'),
('Аргеброн', 'Created by BOT', (select id from race where race.name = 'Пеленг'), 33,(select id from username where username.login = 'BOT'), 'peleng2.png'),
('Лафойта', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 33,(select id from username where username.login = 'BOT'), 'fei2.png'),
('Конгами', 'Created by BOT', (select id from race where race.name = 'Гаалец'), -38,(select id from username where username.login = 'BOT'), 'gaal5.png'),
('Виктор', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -72,(select id from username where username.login = 'BOT'), 'fei2.png'),
('Эллентар-По', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -32,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Эрнан', 'Created by BOT', (select id from race where race.name = 'Человек'), 38,(select id from username where username.login = 'BOT'), 'human4.png'),
('Акеца', 'Created by BOT', (select id from race where race.name = 'Человек'), -3,(select id from username where username.login = 'BOT'), 'human2.png'),
('Ралого', 'Created by BOT', (select id from race where race.name = 'Малок'), 73,(select id from username where username.login = 'BOT'), 'maloc1.png'),
('Рипаципа', 'Created by BOT', (select id from race where race.name = 'Человек'), -87,(select id from username where username.login = 'BOT'), 'human3.png'),
('Ацакша', 'Created by BOT', (select id from race where race.name = 'Человек'), -80,(select id from username where username.login = 'BOT'), 'human1.png'),
('Синклер', 'Created by BOT', (select id from race where race.name = 'Человек'), 87,(select id from username where username.login = 'BOT'), 'human5.png'),
('Коргар', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -95,(select id from username where username.login = 'BOT'), 'peleng5.png'),
('Ланоакия', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 18,(select id from username where username.login = 'BOT'), 'fei2.png'),
('Шелдон', 'Created by BOT', (select id from race where race.name = 'Человек'), -68,(select id from username where username.login = 'BOT'), 'human1.png'),
('Таландо', 'Created by BOT', (select id from race where race.name = 'Пеленг'), 56,(select id from username where username.login = 'BOT'), 'peleng2.png'),
('Янса-Анк', 'Created by BOT', (select id from race where race.name = 'Гаалец'), -15,(select id from username where username.login = 'BOT'), 'gaal4.png'),
('Наран', 'Created by BOT', (select id from race where race.name = 'Гаалец'), -7,(select id from username where username.login = 'BOT'), 'gaal1.png'),
('Зоггарто', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -15,(select id from username where username.login = 'BOT'), 'peleng5.png'),
('Дик', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -13,(select id from username where username.login = 'BOT'), 'fei2.png'),
('Финайла', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 78,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Шугерт', 'Created by BOT', (select id from race where race.name = 'Человек'), -66,(select id from username where username.login = 'BOT'), 'human3.png'),
('Бромшвейгер', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 29,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Греф', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 51,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Герхард', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 25,(select id from username where username.login = 'BOT'), 'fei4.png'),
('Асселцак', 'Created by BOT', (select id from race where race.name = 'Человек'), -24,(select id from username where username.login = 'BOT'), 'human4.png'),
('Грумандо', 'Created by BOT', (select id from race where race.name = 'Пеленг'), 97,(select id from username where username.login = 'BOT'), 'peleng1.png'),
('Пехи Монца', 'Created by BOT', (select id from race where race.name = 'Человек'), 68,(select id from username where username.login = 'BOT'), 'human5.png');


---------

insert into spaceship(name, spaceship_type_id, pilot_id, system_id, image) values
('Грузовой транспорт Аргатру', (select id from spaceship_type where spaceship_type.name = 'Грузовой транспорт'), (select id from pilot where pilot.name = 'Аргатру'),20,'2MalocT.png'),
('Грузовой транспорт Гааори', (select id from spaceship_type where spaceship_type.name = 'Дипломатический корабль'), (select id from pilot where pilot.name = 'Гааори'),24,'2GaalL.png'),
('Пиратский корабль Леестак', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Леестак'),24,'2GaalP.png'),
('Пиратский корабль Ашпарака', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Ашпарака'),22,'2PelengP.png'),
('Пассажирский Лайнер Рорра-Аки', (select id from spaceship_type where spaceship_type.name = 'Дипломатический корабль'), (select id from pilot where pilot.name = 'Рорра-Аки'),5,'2GaalT.png'),
('Дипломатический корабль Моларбо', (select id from spaceship_type where spaceship_type.name = 'Дипломатический корабль'), (select id from pilot where pilot.name = 'Моларбо'),5,'2MalocW.png'),
('Пиратский корабль Раноялми', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Раноялми'),4,'2FeiP.png'),
('Пиратский корабль Гроомак', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Гроомак'),8,'2GaalP.png'),
('Пиратский корабль Урааган', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Урааган'),8,'2GaalP.png'),
('Пассажирский Лайнер То-Олак', (select id from spaceship_type where spaceship_type.name = 'Грузовой транспорт'), (select id from pilot where pilot.name = 'То-Олак'),4,'2GaalW.png'),
('Корабль Рейнджера Метилла', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Метилла'),17,'2FeiR.png'),
('Дипломатический корабль Лошашка', (select id from spaceship_type where spaceship_type.name = 'Грузовой транспорт'), (select id from pilot where pilot.name = 'Лошашка'),4,'2PelengT.png'),
('Дипломатический корабль Артелга', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Артелга'),14,'2PelengL.png'),
('Пассажирский Лайнер Зерогуд', (select id from spaceship_type where spaceship_type.name = 'Военный корабль'), (select id from pilot where pilot.name = 'Зерогуд'),12,'2MalocL.png'),
('Военный корабль Саб', (select id from spaceship_type where spaceship_type.name = 'Военный корабль'), (select id from pilot where pilot.name = 'Саб'),20,'2PeopleL.png'),
('Пассажирский Лайнер Келлис', (select id from spaceship_type where spaceship_type.name = 'Грузовой транспорт'), (select id from pilot where pilot.name = 'Келлис'),6,'2GaalD.png'),
('Пиратский корабль Ошира Бен', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Ошира Бен'),16,'2PelengP.png'),
('Грузовой транспорт Лаки Хан', (select id from spaceship_type where spaceship_type.name = 'Военный корабль'), (select id from pilot where pilot.name = 'Лаки Хан'),7,'2PelengW.png'),
('Пиратский корабль Лианарик', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Лианарик'),23,'2FeiP.png'),
('Корабль Рейнджера Келобар', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Келобар'),6,'2MalocR.png'),
('Пиратский корабль Цапиль', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Цапиль'),18,'2PelengP.png'),
('Пиратский корабль Онаемлак', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Онаемлак'),11,'2FeiP.png'),
('Военный корабль Элеомис', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Элеомис'),2,'2FeiT.png'),
('Грузовой транспорт Прооглин', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Прооглин'),11,'2GaalT.png'),
('Пассажирский Лайнер Кучма Хан', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Кучма Хан'),21,'2PeopleL.png'),
('Флагман Константин', (select id from spaceship_type where spaceship_type.name = 'Флагман'), (select id from pilot where pilot.name = 'Константин'),14,'2PeopleBW.png'),
('Дипломатический корабль Тандрон', (select id from spaceship_type where spaceship_type.name = 'Грузовой транспорт'), (select id from pilot where pilot.name = 'Тандрон'),9,'2MalocL.png'),
('Пиратский корабль Умта Уоллис', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Умта Уоллис'),6,'2FeiP.png'),
('Корабль Рейнджера Лаоффик', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Лаоффик'),12,'2FeiR.png'),
('Пиратский корабль Илик', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Илик'),22,'2FeiP.png'),
('Военный корабль Рийомайцах', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Рийомайцах'),19,'2PelengW.png'),
('Пиратский корабль Удондер', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Удондер'),11,'2MalocP.png'),
('Грузовой транспорт Аргеброн', (select id from spaceship_type where spaceship_type.name = 'Военный корабль'), (select id from pilot where pilot.name = 'Аргеброн'),7,'2PelengD.png'),
('Военный корабль Лафойта', (select id from spaceship_type where spaceship_type.name = 'Военный корабль'), (select id from pilot where pilot.name = 'Лафойта'),20,'2FeiL.png'),
('Пиратский корабль Конгами', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Конгами'),25,'2GaalP.png'),
('Пиратский корабль Виктор', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Виктор'),10,'2FeiP.png'),
('Пиратский корабль Эллентар-По', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Эллентар-По'),18,'2FeiP.png'),
('Дипломатический корабль Эрнан', (select id from spaceship_type where spaceship_type.name = 'Грузовой транспорт'), (select id from pilot where pilot.name = 'Эрнан'),18,'2PeopleW.png'),
('Военный корабль Акеца', (select id from spaceship_type where spaceship_type.name = 'Военный корабль'), (select id from pilot where pilot.name = 'Акеца'),6,'2PeopleW.png'),
('Корабль Рейнджера Ралого', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Ралого'),22,'2MalocR.png'),
('Пиратский корабль Рипаципа', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Рипаципа'),22,'2PeopleP.png'),
('Пиратский корабль Ацакша', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Ацакша'),20,'2PeopleP.png'),
('Корабль Рейнджера Синклер', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Синклер'),15,'2PeopleR.png'),
('Пиратский корабль Коргар', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Коргар'),24,'2PelengP.png'),
('Дипломатический корабль Ланоакия', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Ланоакия'),24,'2FeiD.png'),
('Пиратский корабль Шелдон', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Шелдон'),2,'2PeopleP.png'),
('Корабль Рейнджера Таландо', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Таландо'),25,'2PelengR.png'),
('Военный корабль Янса-Анк', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Янса-Анк'),6,'2GaalT.png'),
('Пассажирский Лайнер Наран', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Наран'),7,'2GaalW.png'),
('Грузовой транспорт Зоггарто', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Зоггарто'),15,'2PelengW.png'),
('Военный корабль Дик', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Дик'),9,'2FeiL.png'),
('Корабль Рейнджера Финайла', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Финайла'),11,'2FeiR.png'),
('Пиратский корабль Шугерт', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Шугерт'),16,'2PeopleP.png'),
('Грузовой транспорт Бромшвейгер', (select id from spaceship_type where spaceship_type.name = 'Грузовой транспорт'), (select id from pilot where pilot.name = 'Бромшвейгер'),6,'2FeiT.png'),
('Корабль Рейнджера Греф', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Греф'),13,'2FeiR.png'),
('Грузовой транспорт Герхард', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Герхард'),24,'2FeiL.png'),
('Пиратский корабль Асселцак', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Асселцак'),13,'2PeopleP.png'),
('Флагман Грумандо', (select id from spaceship_type where spaceship_type.name = 'Флагман'), (select id from pilot where pilot.name = 'Грумандо'),15,'2PelengBW.png'),
('Корабль Рейнджера Пехи Монца', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Пехи Монца'),16,'2PeopleR.png');

-----------BASES----------
insert into spacebase (name, spacebase_type_id, system_id, coord_x, coord_y) values
('Союз', (select id from spacebase_type where spacebase_type.name = 'Центр рейнджеров'),(select id from system where system.name = 'Селиостр'), -1091, -1082),
('Странник', (select id from spacebase_type where spacebase_type.name = 'Центр рейнджеров'),(select id from system where system.name = 'Бетельгейзе'), -1087, 860),
('Мечтатель', (select id from spacebase_type where spacebase_type.name = 'Центр рейнджеров'),(select id from system where system.name = 'Маркаб'), -147, -23),
('Лисица', (select id from spacebase_type where spacebase_type.name = 'Черный рынок'),(select id from system where system.name = 'Наккар'), -135, -187),
('Ужастик', (select id from spacebase_type where spacebase_type.name = 'Черный рынок'),(select id from system where system.name = 'Муррац'), -1068, 427),
('Террор', (select id from spacebase_type where spacebase_type.name = 'Черный рынок'),(select id from system where system.name = 'Таллот'), 774, -520),
('Альфа', (select id from spacebase_type where spacebase_type.name = 'Военная база'),(select id from system where system.name = 'Хезе'), -235, -1073),
('Бета', (select id from spacebase_type where spacebase_type.name = 'Военная база'),(select id from system where system.name = 'Фелгест'), -1040, -456),
('Гамма', (select id from spacebase_type where spacebase_type.name = 'Военная база'),(select id from system where system.name = 'Атрия'), -325, -923),
('Квантум', (select id from spacebase_type where spacebase_type.name = 'Научная станция'),(select id from system where system.name = 'Гевер'), 491, 601),
('Октан-99', (select id from spacebase_type where spacebase_type.name = 'Научная станция'),(select id from system where system.name = 'Укфал'), -617, 795),
('Органики', (select id from spacebase_type where spacebase_type.name = 'Научная станция'),(select id from system where system.name = 'Сезмен'), -305, 209),
('Эконом', (select id from spacebase_type where spacebase_type.name = 'Бизнес-центр'),(select id from system where system.name = 'Тураис'), -128, -59),
('Инкомат', (select id from spacebase_type where spacebase_type.name = 'Бизнес-центр'),(select id from system where system.name = 'Завия'), 1059, 928),
('Инвестор', (select id from spacebase_type where spacebase_type.name = 'Бизнес-центр'),(select id from system where system.name = 'Краа'), -671, -74),
('Стоматологии', (select id from spacebase_type where spacebase_type.name = 'Медицинский центр'),(select id from system where system.name = 'Юфалли'), -1099, -562),
('Тихая обитель', (select id from spacebase_type where spacebase_type.name = 'Медицинский центр'),(select id from system where system.name = 'Солнце'), 83, 819),
('Последнее пристанище', (select id from spacebase_type where spacebase_type.name = 'Медицинский центр'),(select id from system where system.name = 'Диадема'), -1002, 221),
('Доминион',(select id from spacebase_type where spacebase_type.name = 'Доминион'), (select id from system where system.name = 'Денеб'),-1233, -1000);


insert into action_type
(name, action_impact)
values ('Сделать очень плохо', -3),
       ('Сделать  плохо', -1),
       ('Сделать нормально', 0),
       ('Сделать хорошо', 1),
       ('Сделать очень хорошо', 3);

insert into action
(action_description, pilot_id, action_type_id)
values ('Было совершено ограбление торгового судна. Обошлось без жертв.',
        2,
        (select id from action_type where action_type.name = 'Сделать  плохо'));
