insert into username
values (default, 'BOT', 'LOGIN'),
       (default, 'SuperAboba9000', '$2a$06$FjtentBpK4MtTF.JVIbNA.V6AMuAbQupsP4TEBsBHz0g05rzGfDDG');


insert into spaceship_type
values (default,
        'Грузовой транспорт',
        'Медленный, бронированный и грузоподъёмный. Слабое вооружения.'),
       (default,
        'Дипломатический корабль',
        'Быстрый, бронированный, с неплохим вооружением. Используется для дипломатический миссий.'),
       (default,
        'Пассажирский Лайнер',
        'Среднескоростной и бронированный, служит для транспортировки пассажиров. Слабое вооружения.'),
       (default,
        'Военный корабль',
        'корабль средней скорости, хорошее вооружение, хорошая броня.'),
       (default,
        'Пиратский корабль',
        'Быстрый корабль, среднее вооружение, но слабая защита корпуса. Лучшее что' ||
        ' можно было собрать из космичекого мусора'),
       (default,
        'Корабль Рейнджера',
        'Корабль средней скорости, хорошее вооружение и броня.'),
       (default,
        'Флагман',
        'Является крупным военным кораблём. Крайне медлительный, но имеет прекрасную прочность' ||
        'корпуса и передовое вооружение');

insert into spacebase_type
values (default,
        'Медицинский центр',
        'Медицинский центр - место где можно подправить руки, ноги и другие конечности.',
        'MB.png',
        -32,
        100),
       (default,
        'Бизнес-центр',
        'Космический банк. Ну что о нём можно сказать... Работает как любой другой банк.',
        'BC.png',
        0,
        100),
       (default,
        'Военная база',
        'Космическая военная база. О ней мало какой-либо информации ввиду её секретности.',
        'WB.png',
        75,
        100),
       (default,
        'Черный рынок',
        'Место скопления воров и мошенников. Здесь можно прибрести не совсем законные вещи.',
        'PB.png',
        -100,
        100),
       (default,
        'Научная станция',
        'Научная станция - отличное место для приобретения передовых технологий.',
        'SB.png',
        20,
        100),
       (default, 'Доминион',
        'Удивительно, но у пиратского союза также есть своя космическая база. Благодаря своей ' ||
        'удивительной технологии менять своё месторасположение в галактике, на космическую базу Доминион' ||
        ' ещё никому не удалось напасть.',
        'Domin.png',
        -100,
        -25),
       (default,
        'Центр рейнджеров',
        'Проводят классификацию рейнджеров. Информируют планеты о деятельности тех или иных рейнджеров',
        'RB.png',
        25,
        100);

insert into politics
values (default,
        'Абсолютная монархия',
        'Форма правления или государственного устройства, при котором пост официального главой государства закреплён за монархом.'),
       (default,
        'Демократия',
        'Форма правления, при которой народ имеет право выбирать своих правящих законодателей'),
       (default,
        'Анархия',
        'Здесь нет власти, правил или законов. Однако слабые все равно вынуждены подчиняться сильным'),
       (default,
        'Республика',
        'Форма государственного правления, при которой все органы государственной власти либо избираются на определённый срок,' ||
        ' либо формируются общенациональными представительными учреждениями (например, парламентом), а граждане обладают личными и политическими правами.');

insert into economics
values (default, 'Аграрная', 'Преобладает сельское хозяйство.'),
       (default, 'Индустриальная', 'Преобладает промышленность с гибкими динамичными структурами.'),
       (default, 'Смешанная', 'Развитие аграрной и индустриальной промышленностей идёт равномено.');

insert into race
values (default, 'Человек', 'Две руки, две ноги - на макаку похож.'),
       (default, 'Фэяне', 'Раса гуманоидов-гермафродитов с большим мозгом и фасеточными глазами.'),
       (default, 'Малок',
        'Крупные, мощного телосложения гуманоиды. Для них характерна огромная физическая сила, ' || 'выносливость, ' ||
        'Высокая сопротивляемость природным факторам, не слишком активная мыслительная деятельность.'),
       (default, 'Гаалец',
        'Гуманоиды, тысячелетиями модифицирующие свою биологическую форму путем генетических модификаций эмбрионов.'),
       (default, 'Пеленг',
        'Относятся к виду жаброшеих амфибий. Этот вид существ одинаково хорошо приспособлен для обитания как в жидкой среде, так и на суше.');


insert into planet(name, citizens, politics_id, economics_id, system_id, coord_x, coord_y, image) values
('Купава', 8030, 1, 1, (select system.id from system where system.name = 'Витта Прайонис'), 846, -344, 'p7.png'),
('Селище', 7809, 2, 2, (select system.id from system where system.name = 'Витта Прайонис'), 289, -610, 'p8.png'),
('Борок', 0, null, null, (select system.id from system where system.name = 'Витта Прайонис'), -144, 326, 'p1.png'),

('Арабан', 0, null, null, (select system.id from system where system.name = 'Шеат'), 587, -790, 'p2.png'),
('Хокку', 0, null, null, (select system.id from system where system.name = 'Шеат'), -836, -812, 'p1.png'),
('Бинард', 8050, 3, 2, (select system.id from system where system.name = 'Шеат'), 366, -851, 'p6.png'),
('Тумыр', 0, null, null, (select system.id from system where system.name = 'Шеат'), -313, 385, 'p6.png'),
('Шхоут', 0, null, null, (select system.id from system where system.name = 'Шеат'), -455, -241, 'p8.png'),
('Опара', 294, 3, 1, (select system.id from system where system.name = 'Шеат'), -485, -714, 'p5.png'),

('Луфарь', 8061, 2, 2, (select system.id from system where system.name = 'Краа'), -526, 307, 'p5.png'),
('Бэнди', 3656, 3, 2, (select system.id from system where system.name = 'Краа'), 751, -509, 'p2.png'),
('Ясенец', 8870, 3, 2, (select system.id from system where system.name = 'Краа'), 231, -943, 'p5.png'),
('Черут', 554, 1, 2, (select system.id from system where system.name = 'Краа'), 162, -637, 'p7.png'),
('Клинт', 914, 2, 2, (select system.id from system where system.name = 'Краа'), -218, -768, 'p6.png'),
('Мятие', 0, null, null, (select system.id from system where system.name = 'Краа'), -397, 782, 'p1.png'),

('Графин', 9209, 1, 1, (select system.id from system where system.name = 'Тураис'), 65, 876, 'p6.png'),
('Ташист', 0, null, null, (select system.id from system where system.name = 'Тураис'), -567, 87, 'p8.png'),
('Биолит', 9305, 2, 2, (select system.id from system where system.name = 'Тураис'), -71, 369, 'p5.png'),

('Бахта', 9360, 3, 2, (select system.id from system where system.name = 'Хезе'), -328, 23, 'p8.png'),
('Порте', 0, null, null, (select system.id from system where system.name = 'Хезе'), -385, 57, 'p7.png'),
('Абихит', 0, null, null, (select system.id from system where system.name = 'Хезе'), 489, 860, 'p3.png'),
('Колбен', 5084, 1, 2, (select system.id from system where system.name = 'Хезе'), 345, 354, 'p7.png'),
('Дудник', 0, null, null, (select system.id from system where system.name = 'Хезе'), -290, 645, 'p5.png'),

('Нафтид', 7299, 3, 1, (select system.id from system where system.name = 'Таллот'), 935, -402, 'p7.png'),
('Бирка', 2540, 2, 1, (select system.id from system where system.name = 'Таллот'), -921, 522, 'p2.png'),
('Немет', 0, null, null, (select system.id from system where system.name = 'Таллот'), -722, 708, 'p7.png'),
('Чиамба', 1647, 2, 1, (select system.id from system where system.name = 'Таллот'), -159, -733, 'p2.png'),

('Ибогин', 0, null, null, (select system.id from system where system.name = 'Ругулус'), -378, 212, 'p5.png'),
('Лаурат', 2267, 3, 2, (select system.id from system where system.name = 'Ругулус'), 340, 422, 'p2.png'),
('Осечка', 6589, 1, 1, (select system.id from system where system.name = 'Ругулус'), 733, -621, 'p7.png'),
('Смизит', 7503, 3, 2, (select system.id from system where system.name = 'Ругулус'), 898, -646, 'p8.png'),
('Зевок', 6218, 3, 2, (select system.id from system where system.name = 'Ругулус'), 160, -339, 'p7.png'),
('Аршин', 0, null, null, (select system.id from system where system.name = 'Ругулус'), 923, 276, 'p1.png'),

('Накол', 2911, 3, 2, (select system.id from system where system.name = 'Гевер'), -527, 786, 'p3.png'),
('Лесище', 0, null, null, (select system.id from system where system.name = 'Гевер'), -82, 39, 'p4.png'),
('Фронт', 5642, 1, 1, (select system.id from system where system.name = 'Гевер'), 332, -863, 'p4.png'),
('Стант', 0, null, null, (select system.id from system where system.name = 'Гевер'), 743, 406, 'p4.png'),
('Дачка', 0, null, null, (select system.id from system where system.name = 'Гевер'), -665, 803, 'p5.png'),

('Гусли', 0, null, null, (select system.id from system where system.name = 'Наккар'), 900, -230, 'p6.png'),
('Феддан', 7777, 1, 2, (select system.id from system where system.name = 'Наккар'), 431, 479, 'p8.png'),
('Лобки', 0, null, null, (select system.id from system where system.name = 'Наккар'), -14, -121, 'p8.png'),
('Сечат', 0, null, null, (select system.id from system where system.name = 'Наккар'), 741, -315, 'p6.png'),

('Заплыв', 7503, 1, 2, (select system.id from system where system.name = 'Селиостр'), -845, 608, 'p4.png'),
('Квагга', 3675, 1, 1, (select system.id from system where system.name = 'Селиостр'), 370, 794, 'p4.png'),
('Прожог', 923, 2, 2, (select system.id from system where system.name = 'Селиостр'), 835, 652, 'p4.png'),
('Список', 5648, 1, 1, (select system.id from system where system.name = 'Селиостр'), -854, -6, 'p2.png'),
('Притча', 0, null, null, (select system.id from system where system.name = 'Селиостр'), 441, -209, 'p5.png'),
('Калата', 5310, 3, 2, (select system.id from system where system.name = 'Селиостр'), 742, 890, 'p4.png'),

('Виньет', 0, null, null, (select system.id from system where system.name = 'Укфал'), -327, 466, 'p3.png'),
('Крайер', 0, null, null, (select system.id from system where system.name = 'Укфал'), 949, -173, 'p2.png'),
('Нажим', 0, null, null, (select system.id from system where system.name = 'Укфал'), -941, 61, 'p4.png'),
('Нельма', 5488, 2, 1, (select system.id from system where system.name = 'Укфал'), -620, 293, 'p3.png'),

('Молот', 0, null, null, (select system.id from system where system.name = 'Юфалли'), -236, 46, 'p2.png'),
('Период', 0, null, null, (select system.id from system where system.name = 'Юфалли'), -284, 186, 'p7.png'),
('Амбре', 0, null, null, (select system.id from system where system.name = 'Юфалли'), 961, -930, 'p6.png'),
('Гаюин', 6154, 3, 2, (select system.id from system where system.name = 'Юфалли'), 669, 549, 'p4.png'),
('Вейка', 0, null, null, (select system.id from system where system.name = 'Юфалли'), 227, 234, 'p6.png'),
('Пекло', 4090, 1, 1, (select system.id from system where system.name = 'Юфалли'), 642, 26, 'p1.png'),

('Нерине', 5561, 2, 2, (select system.id from system where system.name = 'Денеб'), 123, -247, 'p8.png'),
('Астрея', 6844, 2, 1, (select system.id from system where system.name = 'Денеб'), 950, -725, 'p5.png'),
('Полдин', 0, null, null, (select system.id from system where system.name = 'Денеб'), -159, -376, 'p6.png'),
('Анурез', 566, 3, 2, (select system.id from system where system.name = 'Денеб'), -334, 602, 'p3.png'),
('Оарион', 5293, 1, 1, (select system.id from system where system.name = 'Денеб'), -759, 368, 'p7.png'),

('Мистик', 7235, 2, 2, (select system.id from system where system.name = 'Атрия'), -723, -304, 'p3.png'),
('Субаг', 5671, 3, 2, (select system.id from system where system.name = 'Атрия'), -234, 185, 'p4.png'),
('Дудук', 7439, 3, 1, (select system.id from system where system.name = 'Атрия'), -218, 435, 'p4.png'),
('Вишня', 59, 3, 1, (select system.id from system where system.name = 'Атрия'), 620, -205, 'p7.png'),
('Напор', 0, null, null, (select system.id from system where system.name = 'Атрия'), 864, 872, 'p3.png'),

('Дурное', 0, null, null, (select system.id from system where system.name = 'Фелгест'), 749, 674, 'p6.png'),
('Алмаз', 680, 1, 1, (select system.id from system where system.name = 'Фелгест'), -462, 521, 'p6.png'),
('Голак', 8961, 3, 1, (select system.id from system where system.name = 'Фелгест'), -119, 357, 'p2.png'),

('Коржец', 0, null, null, (select system.id from system where system.name = 'Завия'), 908, 445, 'p7.png'),
('Ирида', 8737, 3, 1, (select system.id from system where system.name = 'Завия'), 556, -835, 'p5.png'),
('Фильтр', 2342, 1, 2, (select system.id from system where system.name = 'Завия'), 461, -550, 'p3.png'),

('Вайма', 0, null, null, (select system.id from system where system.name = 'Диадема'), -504, 377, 'p1.png'),
('Отроек', 0, null, null, (select system.id from system where system.name = 'Диадема'), 107, -687, 'p2.png'),
('Ретро', 0, null, null, (select system.id from system where system.name = 'Диадема'), 226, -456, 'p1.png'),
('Годик', 0, null, null, (select system.id from system where system.name = 'Диадема'), -122, 282, 'p7.png'),

('Блогер', 0, null, null, (select system.id from system where system.name = 'Маркаб'), 776, 693, 'p5.png'),
('Павия', 765, 3, 1, (select system.id from system where system.name = 'Маркаб'), -74, 689, 'p5.png'),
('Сутра', 0, null, null, (select system.id from system where system.name = 'Маркаб'), -647, 527, 'p2.png'),
('Подтёк', 7185, 2, 2, (select system.id from system where system.name = 'Маркаб'), -247, 872, 'p5.png'),
('Мубах', 0, null, null, (select system.id from system where system.name = 'Маркаб'), 817, -206, 'p7.png'),

('Кобия', 2314, 1, 2, (select system.id from system where system.name = 'Аркабе'), 872, -272, 'p1.png'),
('Заюшка', 0, null, null, (select system.id from system where system.name = 'Аркабе'), 22, 579, 'p3.png'),
('Венед', 3347, 2, 2, (select system.id from system where system.name = 'Аркабе'), 436, -634, 'p2.png'),
('Менса', 2267, 3, 2, (select system.id from system where system.name = 'Аркабе'), -312, -37, 'p1.png'),
('Протес', 2487, 3, 2, (select system.id from system where system.name = 'Аркабе'), 755, 894, 'p1.png'),

('Ввозка', 2043, 3, 1, (select system.id from system where system.name = 'Канопус'), 526, 545, 'p2.png'),
('Гипюр', 5464, 1, 2, (select system.id from system where system.name = 'Канопус'), -414, 726, 'p5.png'),
('Держак', 5315, 3, 1, (select system.id from system where system.name = 'Канопус'), -857, -361, 'p5.png'),
('Наусец', 0, null, null, (select system.id from system where system.name = 'Канопус'), 519, -676, 'p8.png'),
('Форинт', 6983, 3, 2, (select system.id from system where system.name = 'Канопус'), 165, -147, 'p8.png'),
('Хилый', 6113, 1, 1, (select system.id from system where system.name = 'Канопус'), -382, 313, 'p2.png'),

('Кекур', 6893, 1, 1, (select system.id from system where system.name = 'Сезмен'), 13, -896, 'p2.png'),
('Венок', 1371, 1, 1, (select system.id from system where system.name = 'Сезмен'), -956, -6, 'p7.png'),
('Тагиш', 0, null, null, (select system.id from system where system.name = 'Сезмен'), 913, 677, 'p7.png'),
('Ноноза', 1728, 2, 2, (select system.id from system where system.name = 'Сезмен'), -739, 935, 'p1.png'),

('Могель', 778, 3, 2, (select system.id from system where system.name = 'Муррац'), 0, -319, 'p2.png'),
('Зажин', 3458, 2, 1, (select system.id from system where system.name = 'Муррац'), 192, -718, 'p2.png'),
('Меддах', 1496, 2, 2, (select system.id from system where system.name = 'Муррац'), 821, -446, 'p1.png'),
('Ворон', 7688, 2, 1, (select system.id from system where system.name = 'Муррац'), 728, 161, 'p4.png'),
('Понит', 0, null, null, (select system.id from system where system.name = 'Муррац'), -712, 226, 'p3.png'),

('Жница', 8606, 1, 2, (select system.id from system where system.name = 'Бетельгейзе'), 276, -311, 'p5.png'),
('Веллон', 6397, 1, 1, (select system.id from system where system.name = 'Бетельгейзе'), 460, 714, 'p6.png'),
('Ворьё', 2794, 2, 2, (select system.id from system where system.name = 'Бетельгейзе'), -936, -365, 'p1.png'),
('Завязь', 9692, 2, 1, (select system.id from system where system.name = 'Бетельгейзе'), -185, -434, 'p6.png'),
('Алдар', 0, null, null, (select system.id from system where system.name = 'Бетельгейзе'), 185, -388, 'p7.png'),
('Аптих', 2166, 2, 2, (select system.id from system where system.name = 'Бетельгейзе'), 820, 924, 'p6.png'),

('Бекас', 0, null, null, (select system.id from system where system.name = 'Кефрон'), 217, -917, 'p2.png'),
('Геката', 5062, 1, 2, (select system.id from system where system.name = 'Кефрон'), -107, 191, 'p8.png'),
('Твердо', 1258, 2, 2, (select system.id from system where system.name = 'Кефрон'), 941, 624, 'p7.png'),
('Повтор', 1841, 1, 2, (select system.id from system where system.name = 'Кефрон'), -814, -740, 'p5.png'),
('Комик', 0, null, null, (select system.id from system where system.name = 'Кефрон'), -516, 768, 'p1.png'),

('Меркурий', 0, null, null, (select system.id from system where system.name = 'Солнце'), 181, -1249, 'solar/mercury.png'),
('Венера', 1265, 1, 2, (select system.id from system where system.name = 'Солнце'), 814, -1140, 'solar/venus.png'),
('Земля', 8340, 2, 2, (select system.id from system where system.name = 'Солнце'), -215, 405, 'solar/earth.png'),
('Марс', 387, 2, 2, (select system.id from system where system.name = 'Солнце'), -434, -138, 'solar/mars.png'),
('Юпитер', 0, null, null, (select system.id from system where system.name = 'Солнце'), -1244, 585, 'solar/jupiter.png'),
('Сатурн', 0, null, null, (select system.id from system where system.name = 'Солнце'), -330, -282, 'solar/saturn.png'),
('Уран', 0, null, null, (select system.id from system where system.name = 'Солнце'), -1033, 1297, 'solar/uranus.png'),
('Нептун', 0, null, null, (select system.id from system where system.name = 'Солнце'), 531, -486, 'solar/neptune.png');

-------SYSTEMS---------
insert into sector(name) values
('Атланта'),
('Фаави'),
('Таолис'),
('Нароби'),
('Реггет'),
('Эльта'),
('Карагон');


-------PLANETS-------

insert into system(name, sector_id, image) values
('Витта Прайонис', (select sector.id from sector where sector.name = 'Атланта'), 's10.png'),
('Шеат', (select sector.id from sector where sector.name = 'Атланта'), 's13.png'),
('Краа', (select sector.id from sector where sector.name = 'Атланта'), 's7.png'),
('Тураис', (select sector.id from sector where sector.name = 'Атланта'), 's6.png'),

('Хезе', (select sector.id from sector where sector.name = 'Фаави'), 's8.png'),
('Таллот', (select sector.id from sector where sector.name = 'Фаави'), 's8.png'),
('Ругулус', (select sector.id from sector where sector.name = 'Фаави'), 's11.png'),

('Гевер', (select sector.id from sector where sector.name = 'Таолис'), 's1.png'),
('Наккар', (select sector.id from sector where sector.name = 'Таолис'), 's2.png'),
('Селиостр', (select sector.id from sector where sector.name = 'Таолис'), 's8.png'),

('Укфал', (select sector.id from sector where sector.name = 'Нароби'), 's11.png'),
('Юфалли', (select sector.id from sector where sector.name = 'Нароби'), 's4.png'),
('Денеб', (select sector.id from sector where sector.name = 'Нароби'), 's1.png'),
('Атрия', (select sector.id from sector where sector.name = 'Нароби'), 's8.png'),

('Фелгест', (select sector.id from sector where sector.name = 'Реггет'), 's6.png'),
('Завия', (select sector.id from sector where sector.name = 'Реггет'), 's1.png'),
('Диадема', (select sector.id from sector where sector.name = 'Реггет'), 's5.png'),

('Маркаб', (select sector.id from sector where sector.name = 'Эльта'), 's6.png'),
('Аркабе', (select sector.id from sector where sector.name = 'Эльта'), 's2.png'),
('Канопус', (select sector.id from sector where sector.name = 'Эльта'), 's6.png'),
('Сезмен', (select sector.id from sector where sector.name = 'Эльта'), 's7.png'),
('Муррац', (select sector.id from sector where sector.name = 'Эльта'), 's2.png'),

('Бетельгейзе', (select sector.id from sector where sector.name = 'Карагон'), 's8.png'),
('Кефрон', (select sector.id from sector where sector.name = 'Карагон'), 's7.png'),
('Солнце', (select sector.id from sector where sector.name = 'Карагон'), 's7.png');


-------LIVING_RACES-------

insert into living_races(race_id, planet_id) values
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Купава')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Селище')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Селище')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Бинард')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Опара')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Луфарь')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Луфарь')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Луфарь')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Луфарь')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Бэнди')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Ясенец')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Черут')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Черут')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Клинт')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Клинт')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Клинт')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Клинт')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Графин')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Биолит')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Бахта')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Колбен')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Нафтид')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Бирка')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Чиамба')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Лаурат')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Осечка')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Осечка')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Осечка')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Осечка')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Осечка')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Смизит')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Зевок')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Зевок')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Зевок')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Зевок')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Зевок')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Накол')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Фронт')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Феддан')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Заплыв')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Квагга')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Квагга')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Квагга')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Квагга')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Прожог')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Список')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Список')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Список')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Калата')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Калата')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Калата')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Калата')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Нельма')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Гаюин')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Гаюин')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Гаюин')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Пекло')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Нерине')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Астрея')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Анурез')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Анурез')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Анурез')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Оарион')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Мистик')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Мистик')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Субаг')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Дудук')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Вишня')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Вишня')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Вишня')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Вишня')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Вишня')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Алмаз')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Голак')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Голак')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Голак')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Голак')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Голак')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Ирида')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Ирида')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Ирида')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Ирида')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Ирида')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Фильтр')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Павия')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Подтёк')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Кобия')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Венед')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Менса')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Протес')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Ввозка')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Гипюр')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Гипюр')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Гипюр')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Держак')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Форинт')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Форинт')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Хилый')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Кекур')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Венок')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Ноноза')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Могель')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Зажин')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Меддах')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Ворон')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Жница')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Веллон')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Веллон')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Веллон')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Веллон')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Ворьё')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Завязь')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Аптих')),
((select id from race where race.name = 'Пеленг'),(select id from planet where planet.name = 'Геката')),
((select id from race where race.name = 'Малок'),(select id from planet where planet.name = 'Твердо')),
((select id from race where race.name = 'Фэяне'),(select id from planet where planet.name = 'Твердо')),
((select id from race where race.name = 'Гаалец'),(select id from planet where planet.name = 'Повтор')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Венера')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Земля')),
((select id from race where race.name = 'Человек'),(select id from planet where planet.name = 'Марс'));


---------Pilots---------

insert into pilot(name, description, race_id, rating, owner, image) values
('Элном Кара', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 14,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Шварц', 'Created by BOT', (select id from race where race.name = 'Человек'), -29,(select id from username where username.login = 'BOT'), 'human4.png'),
('Уордер', 'Created by BOT', (select id from race where race.name = 'Человек'), -53,(select id from username where username.login = 'BOT'), 'human4.png'),
('Бандак', 'Created by BOT', (select id from race where race.name = 'Малок'), 22,(select id from username where username.login = 'BOT'), 'maloc5.png'),
('Сиша Цвах', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -73,(select id from username where username.login = 'BOT'), 'peleng3.png'),
('Ула Фитай', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -22,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Агоббор', 'Created by BOT', (select id from race where race.name = 'Пеленг'), 45,(select id from username where username.login = 'BOT'), 'peleng2.png'),
('Цац Илкаш', 'Created by BOT', (select id from race where race.name = 'Пеленг'), 27,(select id from username where username.login = 'BOT'), 'peleng4.png'),
('Громкар', 'Created by BOT', (select id from race where race.name = 'Малок'), -75,(select id from username where username.login = 'BOT'), 'maloc1.png'),
('Кантебо', 'Created by BOT', (select id from race where race.name = 'Малок'), -74,(select id from username where username.login = 'BOT'), 'maloc2.png'),
('Эллафис', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 75,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Ороллин', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 9,(select id from username where username.login = 'BOT'), 'gaal2.png'),
('Урагербо', 'Created by BOT', (select id from race where race.name = 'Малок'), 25,(select id from username where username.login = 'BOT'), 'maloc2.png'),
('Шак Мулда', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -65,(select id from username where username.login = 'BOT'), 'peleng2.png'),
('Ардогар', 'Created by BOT', (select id from race where race.name = 'Пеленг'), 26,(select id from username where username.login = 'BOT'), 'peleng2.png'),
('Цайкан По', 'Created by BOT', (select id from race where race.name = 'Пеленг'), 78,(select id from username where username.login = 'BOT'), 'peleng1.png'),
('Чецелякиш', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -84,(select id from username where username.login = 'BOT'), 'peleng2.png'),
('Элеймак', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -26,(select id from username where username.login = 'BOT'), 'fei2.png'),
('Менайкан', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -38,(select id from username where username.login = 'BOT'), 'fei5.png'),
('Афайкай', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -33,(select id from username where username.login = 'BOT'), 'fei1.png'),
('Антон', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -55,(select id from username where username.login = 'BOT'), 'fei5.png'),
('Улка Нойма', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 84,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Чатлан По', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -37,(select id from username where username.login = 'BOT'), 'peleng5.png'),
('Элеомис', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 34,(select id from username where username.login = 'BOT'), 'fei5.png'),
('Марк', 'Created by BOT', (select id from race where race.name = 'Человек'), 6,(select id from username where username.login = 'BOT'), 'human5.png'),
('Греф', 'Created by BOT', (select id from race where race.name = 'Человек'), -34,(select id from username where username.login = 'BOT'), 'human4.png'),
('Гоббар', 'Created by BOT', (select id from race where race.name = 'Пеленг'), 70,(select id from username where username.login = 'BOT'), 'peleng4.png'),
('Армаддак', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -58,(select id from username where username.login = 'BOT'), 'peleng5.png'),
('Рорра-Аки', 'Created by BOT', (select id from race where race.name = 'Гаалец'), -35,(select id from username where username.login = 'BOT'), 'gaal4.png'),
('Финайла', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -60,(select id from username where username.login = 'BOT'), 'fei5.png'),
('Петер', 'Created by BOT', (select id from race where race.name = 'Человек'), -71,(select id from username where username.login = 'BOT'), 'human2.png'),
('Банарго', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -5,(select id from username where username.login = 'BOT'), 'peleng5.png'),
('Лафойта', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -52,(select id from username where username.login = 'BOT'), 'fei2.png'),
('Рикардо', 'Created by BOT', (select id from race where race.name = 'Человек'), -81,(select id from username where username.login = 'BOT'), 'human3.png'),
('Кимаррак', 'Created by BOT', (select id from race where race.name = 'Гаалец'), -27,(select id from username where username.login = 'BOT'), 'gaal2.png'),
('Рах Цулан', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -31,(select id from username where username.login = 'BOT'), 'peleng1.png'),
('Краамис', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 68,(select id from username where username.login = 'BOT'), 'gaal3.png'),
('Ульрих', 'Created by BOT', (select id from race where race.name = 'Человек'), -22,(select id from username where username.login = 'BOT'), 'human5.png'),
('Дантар', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -66,(select id from username where username.login = 'BOT'), 'peleng2.png'),
('Фа-Арлан', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 41,(select id from username where username.login = 'BOT'), 'gaal4.png'),
('Леонид', 'Created by BOT', (select id from race where race.name = 'Человек'), -32,(select id from username where username.login = 'BOT'), 'human1.png'),
('Кагон', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -7,(select id from username where username.login = 'BOT'), 'peleng3.png'),
('Лука', 'Created by BOT', (select id from race where race.name = 'Человек'), 1,(select id from username where username.login = 'BOT'), 'human5.png'),
('Патрик', 'Created by BOT', (select id from race where race.name = 'Человек'), 79,(select id from username where username.login = 'BOT'), 'human1.png'),
('Урааган', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 95,(select id from username where username.login = 'BOT'), 'gaal5.png'),
('Рацоккиш', 'Created by BOT', (select id from race where race.name = 'Человек'), -37,(select id from username where username.login = 'BOT'), 'human1.png'),
('Робин', 'Created by BOT', (select id from race where race.name = 'Человек'), -75,(select id from username where username.login = 'BOT'), 'human5.png'),
('Экитармиссен', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -52,(select id from username where username.login = 'BOT'), 'fei5.png'),
('Смираан', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 46,(select id from username where username.login = 'BOT'), 'gaal5.png'),
('Уляпка', 'Created by BOT', (select id from race where race.name = 'Человек'), -6,(select id from username where username.login = 'BOT'), 'human5.png'),
('Улла Исни', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 11,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Олиорси', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 38,(select id from username where username.login = 'BOT'), 'fei5.png'),
('Ацка', 'Created by BOT', (select id from race where race.name = 'Человек'), 34,(select id from username where username.login = 'BOT'), 'human4.png'),
('Ахайа', 'Created by BOT', (select id from race where race.name = 'Человек'), 61,(select id from username where username.login = 'BOT'), 'human4.png'),
('Винсент', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 44,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Конгами', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 11,(select id from username where username.login = 'BOT'), 'gaal4.png'),
('Элиамай', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -61,(select id from username where username.login = 'BOT'), 'fei5.png'),
('Ляха Моска', 'Created by BOT', (select id from race where race.name = 'Человек'), 96,(select id from username where username.login = 'BOT'), 'human1.png'),
('Рамисаак', 'Created by BOT', (select id from race where race.name = 'Гаалец'), -36,(select id from username where username.login = 'BOT'), 'gaal4.png'),
('Саанри', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 34,(select id from username where username.login = 'BOT'), 'gaal2.png'),
('Умта Уоллис', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -93,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Асселцак', 'Created by BOT', (select id from race where race.name = 'Человек'), 16,(select id from username where username.login = 'BOT'), 'human3.png'),
('Олмилай', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -39,(select id from username where username.login = 'BOT'), 'fei5.png'),
('Коргар', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -62,(select id from username where username.login = 'BOT'), 'peleng2.png'),
('Эрнан', 'Created by BOT', (select id from race where race.name = 'Человек'), 30,(select id from username where username.login = 'BOT'), 'human2.png'),
('Келлис', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 87,(select id from username where username.login = 'BOT'), 'gaal1.png'),
('Фанниян', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 86,(select id from username where username.login = 'BOT'), 'fei5.png'),
('Икеба', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 8,(select id from username where username.login = 'BOT'), 'gaal1.png'),
('Цантакиш', 'Created by BOT', (select id from race where race.name = 'Человек'), 83,(select id from username where username.login = 'BOT'), 'human2.png'),
('Кучма Хан', 'Created by BOT', (select id from race where race.name = 'Человек'), -32,(select id from username where username.login = 'BOT'), 'human1.png'),
('Орбан', 'Created by BOT', (select id from race where race.name = 'Пеленг'), 95,(select id from username where username.login = 'BOT'), 'peleng3.png'),
('Раа Мати', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 16,(select id from username where username.login = 'BOT'), 'gaal4.png'),
('Хендрик', 'Created by BOT', (select id from race where race.name = 'Человек'), -37,(select id from username where username.login = 'BOT'), 'human5.png'),
('Барогаб', 'Created by BOT', (select id from race where race.name = 'Человек'), 5,(select id from username where username.login = 'BOT'), 'human2.png'),
('Арнольд', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 42,(select id from username where username.login = 'BOT'), 'fei1.png'),
('Белый', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 22,(select id from username where username.login = 'BOT'), 'fei1.png'),
('Алан', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -64,(select id from username where username.login = 'BOT'), 'fei2.png'),
('Алекс', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -77,(select id from username where username.login = 'BOT'), 'fei2.png'),
('Ратеброн', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -70,(select id from username where username.login = 'BOT'), 'peleng2.png'),
('Ролаакан', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 16,(select id from username where username.login = 'BOT'), 'gaal2.png'),
('Лаки Хан', 'Created by BOT', (select id from race where race.name = 'Человек'), 57,(select id from username where username.login = 'BOT'), 'human1.png'),
('Шапацак', 'Created by BOT', (select id from race where race.name = 'Человек'), 85,(select id from username where username.login = 'BOT'), 'human3.png'),
('Синклер', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 22,(select id from username where username.login = 'BOT'), 'fei4.png'),
('Таландо', 'Created by BOT', (select id from race where race.name = 'Пеленг'), -41,(select id from username where username.login = 'BOT'), 'peleng1.png'),
('Царондо', 'Created by BOT', (select id from race where race.name = 'Человек'), 0,(select id from username where username.login = 'BOT'), 'human5.png'),
('Фейриаган', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 95,(select id from username where username.login = 'BOT'), 'fei2.png'),
('Зерогуд', 'Created by BOT', (select id from race where race.name = 'Человек'), -49,(select id from username where username.login = 'BOT'), 'human4.png'),
('Ацубенчик', 'Created by BOT', (select id from race where race.name = 'Человек'), -22,(select id from username where username.login = 'BOT'), 'human5.png'),
('Джохан', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -82,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Элко-Айра', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 88,(select id from username where username.login = 'BOT'), 'fei2.png'),
('Шугерт', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -94,(select id from username where username.login = 'BOT'), 'fei5.png'),
('Ртааток', 'Created by BOT', (select id from race where race.name = 'Гаалец'), -53,(select id from username where username.login = 'BOT'), 'gaal5.png'),
('Даана', 'Created by BOT', (select id from race where race.name = 'Гаалец'), -69,(select id from username where username.login = 'BOT'), 'gaal3.png'),
('Грумандо', 'Created by BOT', (select id from race where race.name = 'Человек'), -14,(select id from username where username.login = 'BOT'), 'human2.png'),
('Лошашка', 'Created by BOT', (select id from race where race.name = 'Человек'), 7,(select id from username where username.login = 'BOT'), 'human4.png'),
('Дик', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -85,(select id from username where username.login = 'BOT'), 'fei5.png'),
('Аристарх', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 91,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Пацакен', 'Created by BOT', (select id from race where race.name = 'Человек'), -80,(select id from username where username.login = 'BOT'), 'human4.png'),
('Артелга', 'Created by BOT', (select id from race where race.name = 'Человек'), 76,(select id from username where username.login = 'BOT'), 'human1.png'),
('Константин', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -10,(select id from username where username.login = 'BOT'), 'fei1.png'),
('Талайко', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -91,(select id from username where username.login = 'BOT'), 'fei5.png'),
('Кудорга', 'Created by BOT', (select id from race where race.name = 'Человек'), -5,(select id from username where username.login = 'BOT'), 'human2.png'),
('Наран', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 70,(select id from username where username.login = 'BOT'), 'gaal1.png'),
('Цишилкис', 'Created by BOT', (select id from race where race.name = 'Человек'), -8,(select id from username where username.login = 'BOT'), 'human5.png'),
('Лобаамир', 'Created by BOT', (select id from race where race.name = 'Гаалец'), -25,(select id from username where username.login = 'BOT'), 'gaal4.png'),
('Памати', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 47,(select id from username where username.login = 'BOT'), 'gaal4.png'),
('Урбаган', 'Created by BOT', (select id from race where race.name = 'Человек'), 2,(select id from username where username.login = 'BOT'), 'human1.png'),
('Иммиотис', 'Created by BOT', (select id from race where race.name = 'Гаалец'), -48,(select id from username where username.login = 'BOT'), 'gaal2.png'),
('Ланоакия', 'Created by BOT', (select id from race where race.name = 'Гаалец'), -85,(select id from username where username.login = 'BOT'), 'gaal4.png'),
('Акеца', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -29,(select id from username where username.login = 'BOT'), 'fei1.png'),
('Раноялми', 'Created by BOT', (select id from race where race.name = 'Фэяне'), 82,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Маза', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -76,(select id from username where username.login = 'BOT'), 'fei3.png'),
('Прирамо', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 37,(select id from username where username.login = 'BOT'), 'gaal5.png'),
('Гадрак', 'Created by BOT', (select id from race where race.name = 'Человек'), -48,(select id from username where username.login = 'BOT'), 'human1.png'),
('Толоймак', 'Created by BOT', (select id from race where race.name = 'Фэяне'), -100,(select id from username where username.login = 'BOT'), 'fei5.png'),
('Унабраг', 'Created by BOT', (select id from race where race.name = 'Человек'), -99,(select id from username where username.login = 'BOT'), 'human5.png'),
('Лаоффик', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 86,(select id from username where username.login = 'BOT'), 'gaal3.png'),
('Онкиар', 'Created by BOT', (select id from race where race.name = 'Гаалец'), 59,(select id from username where username.login = 'BOT'), 'gaal5.png'),
('SuperAboba9000', 'Obama agent', (select id from race where race.name = 'Человек'), 0,(select id from username where username.login = 'SuperAboba9000'), 'human5.png');


---------Spaceships---------

insert into spaceship(name, spaceship_type_id, pilot_id, system_id, image) values
('Пассажирский Лайнер Элном Кара', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Элном Кара'),15,'2FeiL.png'),
('Пиратский корабль Шварц', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Шварц'),17,'2PeopleP.png'),
('Пиратский корабль Уордер', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Уордер'),17,'2PeopleP.png'),
('Дипломатический корабль Бандак', (select id from spaceship_type where spaceship_type.name = 'Дипломатический корабль'), (select id from pilot where pilot.name = 'Бандак'),18,'2MalocD.png'),
('Пиратский корабль Сиша Цвах', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Сиша Цвах'),3,'2PelengP.png'),
('Пиратский корабль Ула Фитай', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Ула Фитай'),9,'2FeiP.png'),
('Корабль Рейнджера Агоббор', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Агоббор'),25,'2PelengR.png'),
('Пассажирский Лайнер Цац Илкаш', (select id from spaceship_type where spaceship_type.name = 'Грузовой транспорт'), (select id from pilot where pilot.name = 'Цац Илкаш'),2,'2PelengT.png'),
('Пиратский корабль Громкар', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Громкар'),14,'2MalocP.png'),
('Пиратский корабль Кантебо', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Кантебо'),15,'2MalocP.png'),
('Корабль Рейнджера Эллафис', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Эллафис'),15,'2FeiR.png'),
('Дипломатический корабль Ороллин', (select id from spaceship_type where spaceship_type.name = 'Военный корабль'), (select id from pilot where pilot.name = 'Ороллин'),8,'2GaalW.png'),
('Дипломатический корабль Урагербо', (select id from spaceship_type where spaceship_type.name = 'Дипломатический корабль'), (select id from pilot where pilot.name = 'Урагербо'),17,'2MalocL.png'),
('Пиратский корабль Шак Мулда', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Шак Мулда'),1,'2PelengP.png'),
('Дипломатический корабль Ардогар', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Ардогар'),5,'2PelengD.png'),
('Корабль Рейнджера Цайкан По', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Цайкан По'),13,'2PelengR.png'),
('Пиратский корабль Чецелякиш', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Чецелякиш'),3,'2PelengP.png'),
('Пиратский корабль Элеймак', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Элеймак'),9,'2FeiP.png'),
('Пиратский корабль Менайкан', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Менайкан'),14,'2FeiP.png'),
('Пиратский корабль Афайкай', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Афайкай'),4,'2FeiP.png'),
('Пиратский корабль Антон', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Антон'),12,'2FeiP.png'),
('Корабль Рейнджера Улка Нойма', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Улка Нойма'),8,'2FeiR.png'),
('Пиратский корабль Чатлан По', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Чатлан По'),20,'2PelengP.png'),
('Грузовой транспорт Элеомис', (select id from spaceship_type where spaceship_type.name = 'Грузовой транспорт'), (select id from pilot where pilot.name = 'Элеомис'),4,'2FeiD.png'),
('Военный корабль Марк', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Марк'),16,'2PeopleD.png'),
('Пиратский корабль Греф', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Греф'),22,'2PeopleP.png'),
('Корабль Рейнджера Гоббар', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Гоббар'),4,'2PelengR.png'),
('Пиратский корабль Армаддак', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Армаддак'),3,'2PelengP.png'),
('Пиратский корабль Рорра-Аки', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Рорра-Аки'),4,'2GaalP.png'),
('Пиратский корабль Финайла', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Финайла'),6,'2FeiP.png'),
('Пиратский корабль Петер', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Петер'),5,'2PeopleP.png'),
('Пассажирский Лайнер Банарго', (select id from spaceship_type where spaceship_type.name = 'Дипломатический корабль'), (select id from pilot where pilot.name = 'Банарго'),3,'2PelengL.png'),
('Пиратский корабль Лафойта', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Лафойта'),9,'2FeiP.png'),
('Пиратский корабль Рикардо', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Рикардо'),11,'2PeopleP.png'),
('Пиратский корабль Кимаррак', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Кимаррак'),21,'2GaalP.png'),
('Пиратский корабль Рах Цулан', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Рах Цулан'),20,'2PelengP.png'),
('Корабль Рейнджера Краамис', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Краамис'),23,'2GaalR.png'),
('Пиратский корабль Ульрих', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Ульрих'),7,'2PeopleP.png'),
('Пиратский корабль Дантар', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Дантар'),14,'2PelengP.png'),
('Корабль Рейнджера Фа-Арлан', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Фа-Арлан'),14,'2GaalR.png'),
('Пиратский корабль Леонид', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Леонид'),17,'2PeopleP.png'),
('Военный корабль Кагон', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Кагон'),10,'2PelengL.png'),
('Грузовой транспорт Лука', (select id from spaceship_type where spaceship_type.name = 'Дипломатический корабль'), (select id from pilot where pilot.name = 'Лука'),7,'2PeopleT.png'),
('Корабль Рейнджера Патрик', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Патрик'),9,'2PeopleR.png'),
('Флагман Урааган', (select id from spaceship_type where spaceship_type.name = 'Флагман'), (select id from pilot where pilot.name = 'Урааган'),13,'2GaalBW.png'),
('Пиратский корабль Рацоккиш', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Рацоккиш'),16,'2PeopleP.png'),
('Пиратский корабль Робин', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Робин'),22,'2PeopleP.png'),
('Пиратский корабль Экитармиссен', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Экитармиссен'),16,'2FeiP.png'),
('Корабль Рейнджера Смираан', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Смираан'),25,'2GaalR.png'),
('Военный корабль Уляпка', (select id from spaceship_type where spaceship_type.name = 'Грузовой транспорт'), (select id from pilot where pilot.name = 'Уляпка'),5,'2PeopleT.png'),
('Дипломатический корабль Улла Исни', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Улла Исни'),20,'2FeiD.png'),
('Пассажирский Лайнер Олиорси', (select id from spaceship_type where spaceship_type.name = 'Грузовой транспорт'), (select id from pilot where pilot.name = 'Олиорси'),12,'2FeiT.png'),
('Пассажирский Лайнер Ацка', (select id from spaceship_type where spaceship_type.name = 'Грузовой транспорт'), (select id from pilot where pilot.name = 'Ацка'),25,'2PeopleL.png'),
('Корабль Рейнджера Ахайа', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Ахайа'),8,'2PeopleR.png'),
('Корабль Рейнджера Винсент', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Винсент'),2,'2FeiR.png'),
('Военный корабль Конгами', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Конгами'),7,'2GaalT.png'),
('Пиратский корабль Элиамай', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Элиамай'),5,'2FeiP.png'),
('Флагман Ляха Моска', (select id from spaceship_type where spaceship_type.name = 'Флагман'), (select id from pilot where pilot.name = 'Ляха Моска'),4,'2PeopleBW.png'),
('Пиратский корабль Рамисаак', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Рамисаак'),17,'2GaalP.png'),
('Грузовой транспорт Саанри', (select id from spaceship_type where spaceship_type.name = 'Дипломатический корабль'), (select id from pilot where pilot.name = 'Саанри'),21,'2GaalT.png'),
('Пиратский корабль Умта Уоллис', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Умта Уоллис'),15,'2FeiP.png'),
('Пассажирский Лайнер Асселцак', (select id from spaceship_type where spaceship_type.name = 'Дипломатический корабль'), (select id from pilot where pilot.name = 'Асселцак'),15,'2PeopleL.png'),
('Пиратский корабль Олмилай', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Олмилай'),10,'2FeiP.png'),
('Пиратский корабль Коргар', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Коргар'),16,'2PelengP.png'),
('Военный корабль Эрнан', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Эрнан'),16,'2PeopleL.png'),
('Корабль Рейнджера Келлис', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Келлис'),14,'2GaalR.png'),
('Корабль Рейнджера Фанниян', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Фанниян'),8,'2FeiR.png'),
('Грузовой транспорт Икеба', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Икеба'),2,'2GaalD.png'),
('Корабль Рейнджера Цантакиш', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Цантакиш'),22,'2PeopleR.png'),
('Пиратский корабль Кучма Хан', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Кучма Хан'),1,'2PeopleP.png'),
('Флагман Орбан', (select id from spaceship_type where spaceship_type.name = 'Флагман'), (select id from pilot where pilot.name = 'Орбан'),19,'2PelengBW.png'),
('Пассажирский Лайнер Раа Мати', (select id from spaceship_type where spaceship_type.name = 'Дипломатический корабль'), (select id from pilot where pilot.name = 'Раа Мати'),20,'2GaalW.png'),
('Пиратский корабль Хендрик', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Хендрик'),17,'2PeopleP.png'),
('Пассажирский Лайнер Барогаб', (select id from spaceship_type where spaceship_type.name = 'Дипломатический корабль'), (select id from pilot where pilot.name = 'Барогаб'),20,'2PeopleW.png'),
('Корабль Рейнджера Арнольд', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Арнольд'),23,'2FeiR.png'),
('Пассажирский Лайнер Белый', (select id from spaceship_type where spaceship_type.name = 'Дипломатический корабль'), (select id from pilot where pilot.name = 'Белый'),3,'2FeiT.png'),
('Пиратский корабль Алан', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Алан'),16,'2FeiP.png'),
('Пиратский корабль Алекс', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Алекс'),3,'2FeiP.png'),
('Пиратский корабль Ратеброн', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Ратеброн'),17,'2PelengP.png'),
('Дипломатический корабль Ролаакан', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Ролаакан'),1,'2GaalL.png'),
('Корабль Рейнджера Лаки Хан', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Лаки Хан'),6,'2PeopleR.png'),
('Корабль Рейнджера Шапацак', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Шапацак'),14,'2PeopleR.png'),
('Пассажирский Лайнер Синклер', (select id from spaceship_type where spaceship_type.name = 'Дипломатический корабль'), (select id from pilot where pilot.name = 'Синклер'),8,'2FeiD.png'),
('Пиратский корабль Таландо', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Таландо'),7,'2PelengP.png'),
('Военный корабль Царондо', (select id from spaceship_type where spaceship_type.name = 'Грузовой транспорт'), (select id from pilot where pilot.name = 'Царондо'),16,'2PeopleT.png'),
('Флагман Фейриаган', (select id from spaceship_type where spaceship_type.name = 'Флагман'), (select id from pilot where pilot.name = 'Фейриаган'),14,'2FeiBW.png'),
('Пиратский корабль Зерогуд', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Зерогуд'),21,'2PeopleP.png'),
('Пиратский корабль Ацубенчик', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Ацубенчик'),2,'2PeopleP.png'),
('Пиратский корабль Джохан', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Джохан'),20,'2FeiP.png'),
('Корабль Рейнджера Элко-Айра', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Элко-Айра'),13,'2FeiR.png'),
('Пиратский корабль Шугерт', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Шугерт'),21,'2FeiP.png'),
('Пиратский корабль Ртааток', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Ртааток'),10,'2GaalP.png'),
('Пиратский корабль Даана', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Даана'),23,'2GaalP.png'),
('Дипломатический корабль Грумандо', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Грумандо'),12,'2PeopleT.png'),
('Дипломатический корабль Лошашка', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Лошашка'),10,'2PeopleL.png'),
('Пиратский корабль Дик', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Дик'),22,'2FeiP.png'),
('Флагман Аристарх', (select id from spaceship_type where spaceship_type.name = 'Флагман'), (select id from pilot where pilot.name = 'Аристарх'),22,'2FeiBW.png'),
('Пиратский корабль Пацакен', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Пацакен'),5,'2PeopleP.png'),
('Корабль Рейнджера Артелга', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Артелга'),6,'2PeopleR.png'),
('Пассажирский Лайнер Константин', (select id from spaceship_type where spaceship_type.name = 'Грузовой транспорт'), (select id from pilot where pilot.name = 'Константин'),7,'2FeiW.png'),
('Пиратский корабль Талайко', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Талайко'),7,'2FeiP.png'),
('Военный корабль Кудорга', (select id from spaceship_type where spaceship_type.name = 'Дипломатический корабль'), (select id from pilot where pilot.name = 'Кудорга'),22,'2PeopleT.png'),
('Корабль Рейнджера Наран', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Наран'),8,'2GaalR.png'),
('Дипломатический корабль Цишилкис', (select id from spaceship_type where spaceship_type.name = 'Грузовой транспорт'), (select id from pilot where pilot.name = 'Цишилкис'),17,'2PeopleW.png'),
('Пиратский корабль Лобаамир', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Лобаамир'),11,'2GaalP.png'),
('Корабль Рейнджера Памати', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Памати'),13,'2GaalR.png'),
('Пассажирский Лайнер Урбаган', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Урбаган'),19,'2PeopleL.png'),
('Пиратский корабль Иммиотис', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Иммиотис'),1,'2GaalP.png'),
('Пиратский корабль Ланоакия', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Ланоакия'),6,'2GaalP.png'),
('Пиратский корабль Акеца', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Акеца'),17,'2FeiP.png'),
('Корабль Рейнджера Раноялми', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Раноялми'),17,'2FeiR.png'),
('Пиратский корабль Маза', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Маза'),19,'2FeiP.png'),
('Дипломатический корабль Прирамо', (select id from spaceship_type where spaceship_type.name = 'Пассажирский Лайнер'), (select id from pilot where pilot.name = 'Прирамо'),13,'2GaalD.png'),
('Пиратский корабль Гадрак', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Гадрак'),13,'2PeopleP.png'),
('Пиратский корабль Толоймак', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Толоймак'),7,'2FeiP.png'),
('Пиратский корабль Унабраг', (select id from spaceship_type where spaceship_type.name = 'Пиратский корабль'), (select id from pilot where pilot.name = 'Унабраг'),23,'2PeopleP.png'),
('Корабль Рейнджера Лаоффик', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Лаоффик'),22,'2GaalR.png'),
('Корабль Рейнджера Онкиар', (select id from spaceship_type where spaceship_type.name = 'Корабль Рейнджера'), (select id from pilot where pilot.name = 'Онкиар'),18,'2GaalR.png'),
('Супер-пупер драндулет', (select id from spaceship_type where spaceship_type.name = 'Флагман'), (select id from pilot where pilot.name = 'SuperAboba9000'),18,'2PelengBW.png');



-----------BASES----------
insert into spacebase (name, spacebase_type_id, system_id, coord_x, coord_y) values
('Союз', (select id from spacebase_type where spacebase_type.name = 'Центр рейнджеров'),(select id from system where system.name = 'Селиостр'), -1091, -1082),
('Странник', (select id from spacebase_type where spacebase_type.name = 'Центр рейнджеров'),(select id from system where system.name = 'Бетельгейзе'), -1087, 860),
('Мечтатель', (select id from spacebase_type where spacebase_type.name = 'Центр рейнджеров'),(select id from system where system.name = 'Маркаб'), -147, -23),
('Лисица', (select id from spacebase_type where spacebase_type.name = 'Черный рынок'),(select id from system where system.name = 'Наккар'), -135, -187),
('Ужастик', (select id from spacebase_type where spacebase_type.name = 'Черный рынок'),(select id from system where system.name = 'Муррац'), -1068, 427),
('Террор', (select id from spacebase_type where spacebase_type.name = 'Черный рынок'),(select id from system where system.name = 'Таллот'), 774, -520),
('Альфа', (select id from spacebase_type where spacebase_type.name = 'Военная база'),(select id from system where system.name = 'Хезе'), -235, -1073),
('Бета', (select id from spacebase_type where spacebase_type.name = 'Военная база'),(select id from system where system.name = 'Фелгест'), -1040, -456),
('Гамма', (select id from spacebase_type where spacebase_type.name = 'Военная база'),(select id from system where system.name = 'Атрия'), -325, -923),
('Квантум', (select id from spacebase_type where spacebase_type.name = 'Научная станция'),(select id from system where system.name = 'Гевер'), 491, 601),
('Октан-99', (select id from spacebase_type where spacebase_type.name = 'Научная станция'),(select id from system where system.name = 'Укфал'), -617, 795),
('Органики', (select id from spacebase_type where spacebase_type.name = 'Научная станция'),(select id from system where system.name = 'Сезмен'), -305, 209),
('Эконом', (select id from spacebase_type where spacebase_type.name = 'Бизнес-центр'),(select id from system where system.name = 'Тураис'), -128, -59),
('Инкомат', (select id from spacebase_type where spacebase_type.name = 'Бизнес-центр'),(select id from system where system.name = 'Завия'), 1059, 928),
('Инвестор', (select id from spacebase_type where spacebase_type.name = 'Бизнес-центр'),(select id from system where system.name = 'Краа'), -671, -74),
('Стоматологии', (select id from spacebase_type where spacebase_type.name = 'Медицинский центр'),(select id from system where system.name = 'Юфалли'), -1099, -562),
('Тихая обитель', (select id from spacebase_type where spacebase_type.name = 'Медицинский центр'),(select id from system where system.name = 'Солнце'), 83, 819),
('Последнее пристанище', (select id from spacebase_type where spacebase_type.name = 'Медицинский центр'),(select id from system where system.name = 'Диадема'), -1002, 221),
('Доминион',(select id from spacebase_type where spacebase_type.name = 'Доминион'), (select id from system where system.name = 'Денеб'),-1233, -1000);


insert into action_type
(name, action_impact)
values ('Сделать очень плохо', -3),
       ('Сделать  плохо', -1),
       ('Сделать нормально', 0),
       ('Сделать хорошо', 1),
       ('Сделать очень хорошо', 3);

-- insert into action
-- (action_description, pilot_id, action_type_id)
-- values ('Было совершено ограбление торгового судна. Обошлось без жертв.',
--         2,
--         (select id from action_type where action_type.name = 'Сделать  плохо'));
